
******************************************************************************
* Johnson Controls Inc. Metasys (TM) DDL Decompiler Release 12.00
* Copyright (C) 2001 Johnson Controls, Inc.   All Rights Reserved.
* Portions Copyright (C) 1987-1988 Lattice Inc.   All Rights Reserved.
*
* Tue May 08 11:10:47 2018
*
* archive decompiled from:
*      C:\Project\Bellatl\win.ini FMSDATA=C:\Project\Bellatl
*
******************************************************************************
@NC "BELLATL", "NC-43"


DCDR "NC-43HW", "730_CH1", "N2 Type DX-9100 Addr-41"
    ADDRESS 41, 1, 3, "DX9100"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 5
*
* Hardware References used = LRS10
*                            DI1
*                            DI2
*                            LRS3
*                            LRS1
*                            LRS2
*                            LRS4
*                            DI3
*                            DI4
*                            DCO1
*                            DCO17
*                            DCO2
*                            DCO18
*                            DCO3
*                            DCO5
*                            DCO4
*                            DO3
*                            DO4
*                            DO5
*                            AI1
*                            AI2
*                            AI3
*                            AI4
*                            ACO1
*                            ACO2
*                            ACO8
*                            ACO3
*                            XT2AO8
*                            XT2AO7
*                            DO7
*                            
*

DCDR "NC-43HW", "730_CH2", "N2 Type DX-9100 Addr-42"
    ADDRESS 42, 1, 3, "DX9100"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 3
*
* Hardware References used = LRS10
*                            DI1
*                            DI2
*                            LRS3
*                            LRS1
*                            LRS2
*                            LRS4
*                            DI3
*                            DI4
*                            DCO13
*                            DCO1
*                            DCO17
*                            DCO2
*                            DCO18
*                            DCO3
*                            DCO5
*                            DCO4
*                            DO3
*                            DO6
*                            DCO29
*                            AI1
*                            AI2
*                            AI3
*                            AI4
*                            ACO1
*                            ACO8
*                            ACO3
*                            DO4
*                            DCO14
*                            XT1AO8
*                            XT1AO7
*                            DO7
*                            
*

DCDR "NC-43HW", "730_CH3", "N2 Type DX-9100 Addr-43"
    ADDRESS 43, 1, 3, "DX9100"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 4
*
* Hardware References used = LRS11
*                            LRS12
*                            LRS13
*                            LRS14
*                            LRS15
*                            LRS17
*                            DI1
*                            DI2
*                            LRS3
*                            LRS1
*                            LRS2
*                            LRS4
*                            LRS16
*                            DI3
*                            LRS18
*                            DI4
*                            DO7
*                            DCO12
*                            DCO6
*                            DCO7
*                            DCO14
*                            DCO8
*                            DO6
*                            DCO1
*                            DCO17
*                            DCO2
*                            DCO18
*                            DCO3
*                            DCO5
*                            DCO4
*                            LRS19
*                            DO4
*                            DO5
*                            AI5
*                            AI6
*                            AI7
*                            AI8
*                            AI1
*                            AI2
*                            AI3
*                            AI4
*                            ACO1
*                            ACO2
*                            OUT2
*                            ACO7
*                            ACO5
*                            ACO6
*                            ACO8
*                            ACO3
*                            ACO4
*                            XT2AO7
*                            
*

N2OPEN "NC-43HW", "730_B-1", "N2 Type UNT Addr-1"
    ADDRESS 1, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    1,  2,  3,  4,  5,  6
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  153
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_B-2", "N2 Dev PCG2621 Addr-26"
    ADDRESS 26, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4,  6
*  BI slots used =    1,  2,  4
*  AO slots used =    2
*  BO slots used =    3
*  IF slots used =  
*  II slots used =  
* IBy slots used =  229
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_B-3", "N2 Dev PCG2621 Addr-27"
    ADDRESS 27, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4,  6
*  BI slots used =    1,  2,  4
*  AO slots used =    2
*  BO slots used =    3
*  IF slots used =  
*  II slots used =  
* IBy slots used =  229
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_1-1", "N2 Type UNT Addr-2"
    ADDRESS 2, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2,  4
*  AO slots used =    2
*  BO slots used =    3
*  IF slots used =  
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_1-2", "N2 Type UNT Addr-3"
    ADDRESS 3, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4,  6
*  BI slots used =    1,  2
*  AO slots used =    2
*  BO slots used =    3
*  IF slots used =  
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_1-3", "N2 Dev PCG2621 Addr-28"
    ADDRESS 28, 1, 3, "AHU"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    7,  8
*  AO slots used =    8
*  BO slots used =    1
*  IF slots used =  
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_2-1", "N2 Type UNT Addr-4"
    ADDRESS 4, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2,  3
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_2-2", "N2 Type UNT Addr-5"
    ADDRESS 5, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4,  6
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_2-3", "N2 Type UNT111-1 Addr-68"
    ADDRESS 68, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_3-1", "N2 Type UNT Addr-6"
    ADDRESS 6, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4,  6
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_3-2", "N2 Type UNT Addr-7"
    ADDRESS 7, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_3-3", "N2 Type UNT111-1 Addr-38"
    ADDRESS 38, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 2
*
*  AI slots used =    1,  2,  3,  4,  5,  6
*  BI slots used =    1,  2,  3
*  AO slots used =    1,  3
*  BO slots used =    3
*  IF slots used =  142,153,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_3-4", "N2 Type UNT111-1 Addr-39"
    ADDRESS 39, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 2
*
*  AI slots used =    1,  2,  3,  4,  5,  6
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  3,  4
*  BO slots used =    3
*  IF slots used =  142,153,237,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_4-1", "N2 Type UNT Addr-9"
    ADDRESS 9, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4,  6
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_4-2", "N2 Type UNT Addr-10"
    ADDRESS 10, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_5-1", "N2 Type UNT Addr-11"
    ADDRESS 11, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_5-2", "N2 Type UNT Addr-12"
    ADDRESS 12, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4,  6
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_5-3", "N2 Type UNT Addr-13"
    ADDRESS 13, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2,  4
*  AO slots used =    2
*  BO slots used =    3
*  IF slots used =  129
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_5-4", "N2 Type UNT Addr-14"
    ADDRESS 14, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_5-5", "N2 Type UNT Addr-15"
    ADDRESS 15, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4,  5
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2,  3
*  BO slots used =    1,  3
*  IF slots used =  142,245,248,252
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

DCDR "NC-43HW", "730_6-1", "N2 Type DX-9100 Addr-16"
    ADDRESS 16, 1, 3, "DX9100"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
* Hardware References used = DI1
*                            DI4
*                            DI2
*                            DI3
*                            DCO1
*                            DO3
*                            AI3
*                            AI4
*                            AI7
*                            AI2
*                            AI5
*                            AI8
*                            ACO7
*                            ACO5
*                            ACO1
*                            OUT1
*                            OUT2
*                            ACO2
*                            OUT9
*                            ACO8
*                            OUT10
*                            
*

DCDR "NC-43HW", "730_6-2", "N2 Type DX-9100 Addr-17"
    ADDRESS 17, 1, 3, "DX9100"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
* Hardware References used = DI1
*                            DI4
*                            DI2
*                            DI3
*                            DCO1
*                            DO3
*                            AI3
*                            AI4
*                            AI2
*                            AI5
*                            ACO7
*                            ACO5
*                            ACO1
*                            OUT1
*                            OUT2
*                            ACO2
*                            OUT9
*                            
*

DCDR "NC-43HW", "730_6-3", "N2 Type DX-9100 Addr-23"
    ADDRESS 23, 1, 3, "DX9100"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
* Hardware References used = DI1
*                            DI4
*                            DI2
*                            DI3
*                            DCO1
*                            DO3
*                            AI3
*                            AI4
*                            AI2
*                            AI5
*                            ACO7
*                            ACO5
*                            ACO1
*                            OUT1
*                            OUT2
*                            ACO2
*                            OUT9
*                            
*

N2OPEN "NC-43HW", "730_6-4", "N2 Type UNT Addr-24"
    ADDRESS 24, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2
*  AO slots used =    1
*  BO slots used =    3
*  IF slots used =  
*  II slots used =  
* IBy slots used =  229
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_6-5", "N2 Type UNT Addr-25"
    ADDRESS 25, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_7-1", "N2 Type UNT Addr-18"
    ADDRESS 18, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    1,  2,  3,  4,  5,  6
*  BI slots used =    1,  2,  3
*  AO slots used =    1,  2,  3
*  BO slots used =    3
*  IF slots used =  142,153,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_7-2", "N2 Type UNT Addr-19"
    ADDRESS 19, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    1,  2,  3,  4,  5
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2,  3
*  BO slots used =    3
*  IF slots used =  142,153,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_7-3", "N2 Type UNT Addr-20"
    ADDRESS 20, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2,  3,  4,  6
*  AO slots used =    1,  2
*  BO slots used =    3,  4
*  IF slots used =  129,247
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_PH1", "N2 Type UNT Addr-22"
    ADDRESS 22, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    1,  2,  3,  5
*  BI slots used =    1,  2
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  129
*  II slots used =  
* IBy slots used =  197,244
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V2-1", "730 2-1 VFD ADD-71"
    ADDRESS 71, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V2-2", "730 2-2 VFD ADD-72"
    ADDRESS 72, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V2-3", "730 2-3 VFD ADD-73"
    ADDRESS 73, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    1,  6
*  BI slots used =    1
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V3-1", "730 3-1 VFD ADD-76"
    ADDRESS 76, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V3-2", "730 3-2 VFD ADD-77"
    ADDRESS 77, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V3-3", "730 3-3 VFD ADD-74"
    ADDRESS 74, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V3-4", "730 3-4 VFD ADD-75"
    ADDRESS 75, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V4-1", "730 4-1 VFD ADD-85"
    ADDRESS 85, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V4-2", "730 4-2 VFD ADD-86"
    ADDRESS 86, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V5-1", "730 5-1 VFD ADD-89"
    ADDRESS 89, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    1
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V5-2", "730 5-2 VFD ADD-90"
    ADDRESS 90, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V5-4", "730 5-4 VFD ADD-91"
    ADDRESS 91, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V5-5", "730 5-5 VFD ADD-92"
    ADDRESS 92, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V6-1", "730 6-1 VFD ADD-93"
    ADDRESS 93, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V6-2", "730 6-2 VFD ADD-94"
    ADDRESS 94, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V6-3", "730 6-3 VFD ADD-95"
    ADDRESS 95, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V6-4", "730 6-4 VFD ADD-96"
    ADDRESS 96, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V7-1", "730 7-1 VFD ADD-99"
    ADDRESS 99, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V7-2", "730 7-2 VFD ADD-100"
    ADDRESS 100, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-43HW", "730_V7-3", "730 7-3 VFD ADD-101"
    ADDRESS 101, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    1,  6
*  BI slots used =    1
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

AI "730_B-1", "OA-TEMP", "Outside Air Temperature"
    HARDWARE "NC-43HW", "730_B-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 1
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 4

CS "730_B-1", "ALL-PNTS", "CS MODEL - Zone Setpoint"
    MODEL "U_MASP5C"
    HARDWARE "NC-43HW", "730_B-1"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 1

BO "730_B-1", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_B-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_B-1", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_B-1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_B-1", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_B-1", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_B-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_B-1", "OFF-NORM", "Unit Off Normal"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 11, 6, 2, 5

AI "730_B-1", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_B-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AI "730_B-1", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_B-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 0.1000000, , , 65.00000, 85.00000, 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

AI "730_B-1", "Z-HUMD", "Zone Humidity"
    HARDWARE "NC-43HW", "730_B-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "% RH", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AI "730_B-1", "MA-TEMP", "Mixed Air Temperature"
    HARDWARE "NC-43HW", "730_B-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "730_B-1", "RACO2-SP", "Return Air CO2 Setpoint"
    HARDWARE "NC-43HW", "730_B-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 153, N
    INIT 900.0000, Y, Y
    UNITS "PPM", 0
    REPORT N, Y, N, N, 5

AI "730_B-1", "RA-CO2", "Return Air CO2 Reading"
    HARDWARE "NC-43HW", "730_B-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "PPM", 0
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "730_B-1", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_B-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_B-1", "H2-ALM", "Hydrogen High Alm Status"
    HARDWARE "NC-43HW", "730_B-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 120, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 14, 6, 2, 5

BI "730_B-1", "WTR-DET", "Water Detection Status"
    HARDWARE "NC-43HW", "730_B-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 6, 6, 2, 5

AOS "730_B-1", "DMP-CMD", "Damper Command"
    HARDWARE "NC-43HW", "730_B-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

AOS "730_B-1", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_B-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

JCB "730_B-1", "OFF_NORM"

AD "730_1-3N", "OA-TEMP", "Outside Air Temperature"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 77.70000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

CS "730_1-3N", "ALL-PNTS", "CS MODEL - Zone Setpoint"
    MODEL "A_100%_C"
~This Model not found in Model Database.
    HARDWARE "NC-43HW", "730_1-3"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_1", "SP_1"
    FORMAT 1

BO "730_1-3N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_1-3"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", Y, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_1-3N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_1-3"
    GRAPHICS 0, 0
    N2OPENHW "BO", 1, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_1-3N", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 0

BI "730_1-3N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_1-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 7
    INIT N, 1, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 0

BD "730_1-3N", "LEAD", "Lead Unit - Always"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, Y, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_1-3N", "LAG", "Lag Unit for 1-1/1-2"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_1-3N", "USE-LAG", "Cycle On Lag Unit"
    GRAPHICS 0, 0
    UNITS "No", "Yes!"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 4

BD "730_1-3N", "STANDBY", "Standby Unit for 1-1/1-2"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_1-3N", "USE-SBY", "Run the Standby Unit"
    GRAPHICS 0, 0
    UNITS "No", "Yes!"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_1-3N", "OFF-NORM", "Unit Off Normal"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 11, 6, 2, 5

BD "730_1-3N", "HI-TEMP", "Unit Zone High Temp"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 12, 6, 2, 5

AD "730_1-3N", "LEAD-HL", "Lead Fail Hi Zone Limit"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 83.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 2, 3, 4

AD "730_1-3N", "LAG-HL", "Lag Cycle Hi Zone Limit"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 80.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 4, 3, 4

AI "730_1-3N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_1-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AI "730_1-3N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_1-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, , , 65.00000, 85.00000, 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

BI "730_1-3N", "WTR-DET", "Water Detect Status"
    HARDWARE "NC-43HW", "730_1-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 8
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 6, 6, 2, 5

JCB "730_1-3N", "SAF_SS"

JCB "730_1-3N", "HI_TEMP"

JCB "730_1-3N", "OFF_NORM"

JCB "730_1-3N", "CYCLE"

AOS "730_1-3N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_1-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 8, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

BD "730-MIS", "EME-SHDN", "HVAC Emergency Shutdown"
    GRAPHICS 0, 0
    UNITS "Off", "On"
    INIT N, N, 1, 0, N, N
    REPORT N, Y, N, N, 10, 6, 1, 5

BD "730-MIS", "FMS-RST", "Reset of Fan Alarms"
    GRAPHICS 0, 0
    UNITS "No", "Reset"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

AI "730-MIS", "OA-TEMP", "Outside Air Temp PH-1"
    HARDWARE "NC-43HW", "730_PH1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 1
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 4

AD "730-MIS", "Econ-SW", "Econ SwitchOver Stpt"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 38.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, , , 0, 0, 0, 5

AD "730-MIS", "ClgOA-LO", "Mech Clg LockOut Stpt"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 32.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, , , 0, 0, 0, 5

AD "730-MIS", "OA-Diff", "Outside Air Differential"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 3.000000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, , , 0, 0, 0, 5

AD "730-MIS", "MA-LoLim", "Mixed Air Low Limit"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 40.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AD "730-MIS", "DA-LoLim", "Discharge Air Low Limit"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 50.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BO "730-MIS", "EXF-DIS2", "1200 Exhaust Fan Disable"
    HARDWARE "NC-43HW", "730_PH1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 244, N
    UNITS "Off", "On", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

JCB "730-MIS", "EME_SHDN"

JCB "730-MIS", "OAT_DUP"

JCB "730-MIS", "FMS_RST"

AD "730_1-2N", "OA-TEMP", "Outside Air Temperature"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 77.70000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

CS "730_1-2N", "ALL-PNTS", "CS MODEL - Zone Setpoint"
    MODEL "U_100%1C"
    HARDWARE "NC-43HW", "730_1-2"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 1

BO "730_1-2N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_1-2"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_1-2N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_1-2"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_1-2N", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_1-2N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_1-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 1, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_1-2N", "LEAD", "Lead Unit"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_1-2N", "LAG", "Lag Unit for 1-1/1-3"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_1-2N", "USE-LAG", "Cycle On Lag Unit"
    GRAPHICS 0, 0
    UNITS "No", "Yes!"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 4

BD "730_1-2N", "STANDBY", "Standby Unit for 1-1/1-3"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, Y, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_1-2N", "USE-SBY", "Run the Standby Unit"
    GRAPHICS 0, 0
    UNITS "No", "Yes!"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_1-2N", "OFF-NORM", "Unit Off Normal"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 11, 6, 2, 5

BD "730_1-2N", "HI-TEMP", "Unit Zone High Temp"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 12, 6, 2, 5

AD "730_1-2N", "LEAD-HL", "Lead Fail Hi Zone Limit"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 83.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 2, 3, 4

AD "730_1-2N", "LAG-HL", "Lag Cycle Hi Zone Limit"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 80.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 4, 3, 4

AI "730_1-2N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_1-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AI "730_1-2N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_1-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, , , 65.00000, 85.00000, 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

AI "730_1-2N", "Z-HUMD", "Zone Humidity"
    HARDWARE "NC-43HW", "730_1-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "% RH", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "730_1-2N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_1-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_1-2N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_1-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

JCB "730_1-2N", "SAF_SS"

JCB "730_1-2N", "HI_TEMP"

JCB "730_1-2N", "OFF_NORM"

JCB "730_1-2N", "CYCLE"

AD "730_1-1N", "OA-TEMP", "Outside Air Temperature"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 77.70000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

CS "730_1-1N", "ALL-PNTS", "CS MODEL - Zone Setpoint"
    MODEL "U_100%1C"
    HARDWARE "NC-43HW", "730_1-1"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 1

BO "730_1-1N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_1-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_1-1N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_1-1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_1-1N", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 0

BI "730_1-1N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_1-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 0

BD "730_1-1N", "LEAD", "Lead Unit"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_1-1N", "LAG", "Lag Unit for 1-2/1-3"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, Y, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_1-1N", "USE-LAG", "Cycle On Lag Unit"
    GRAPHICS 0, 0
    UNITS "No", "Yes!"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 4

BD "730_1-1N", "STANDBY", "Standby Unit for 1-2/1-3"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_1-1N", "USE-SBY", "Run the Standby Unit"
    GRAPHICS 0, 0
    UNITS "No", "Yes!"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_1-1N", "OFF-NORM", "Unit Off Normal"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 11, 6, 2, 5

BD "730_1-1N", "HI-TEMP", "Unit Zone High Temp"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 12, 6, 2, 5

AD "730_1-1N", "LEAD-HL", "Lead Fail Hi Zone Limit"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 83.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 2, 3, 4

AD "730_1-1N", "LAG-HL", "Lag Cycle Hi Zone Limit"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 80.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 4, 3, 4

AI "730_1-1N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_1-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 87.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AI "730_1-1N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_1-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, , , 65.00000, 85.00000, 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

BI "730_1-1N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_1-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_1-1N", "WTR-DET", "Water Detect Status"
    HARDWARE "NC-43HW", "730_1-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 6, 6, 2, 5

AOS "730_1-1N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_1-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

JCB "730_1-1N", "SAF_SS"

JCB "730_1-1N", "HI_TEMP"

JCB "730_1-1N", "OFF_NORM"

JCB "730_1-1N", "CYCLE"

CS "730_MOD", "730_2-1", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-43HW", "730_2-1"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

CS "730_MOD", "730_2-2", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-43HW", "730_2-2"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

CS "730_MOD", "730_5-3", "CS MODEL - Zone Setpoint"
    MODEL "U_100%1C"
    HARDWARE "NC-43HW", "730_5-3"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 1

CS "730_MOD", "730_7-1", "CS MODEL - Act Dis Stpt"
    MODEL "U_MASP5C"
    HARDWARE "NC-43HW", "730_7-1"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

CS "730_MOD", "730_7-2", "CS MODEL - Act Dis Stpt"
    MODEL "U_MASP5C"
    HARDWARE "NC-43HW", "730_7-2"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

CS "730_MOD", "730_PH1", "CS MODEL - Disc Setpoint"
    MODEL "U_MASP7C"
    HARDWARE "NC-43HW", "730_PH1"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 1

CS "NC-43HW", "DX41X100", "Hardware - XT-100 Status"
    MODEL "730_X100"
~This Model not found in Model Database.
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "BD_1", "BD_1"
    FORMAT 1

CS "NC-43HW", "DX41X101", "Hardware - XT-101 Status"
    MODEL "730_X101"
~This Model not found in Model Database.
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "BD_1", "BD_1"
    FORMAT 1

CS "NC-43HW", "DX42X102", "Hardware - XT-102 Status"
    MODEL "730_X102"
~This Model not found in Model Database.
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "BD_1", "BD_1"
    FORMAT 1

CS "NC-43HW", "DX43X103", "Hardware - XT-103 Status"
    MODEL "730_X103"
~This Model not found in Model Database.
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "BD_1", "BD_1"
    FORMAT 1

CS "NC-43HW", "DX43X104", "Hardware - XT-104 Status"
    MODEL "730_X104"
~This Model not found in Model Database.
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "BD_1", "BD_1"
    FORMAT 1

BO "NC-43HW", "C3-SS", "Chiller-3 Sta/Sto C2 DX"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO29", N
    UNITS "Off", "On", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

AD "NC-43HW", "NC43_Idl", "NC-43 CPU Idle Time >70%"
    ASSOCINP "AD", "NONE", "NONE", "IDLE"
    GRAPHICS 0, 0
    UNITS "%", 1, 0.0
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AD "730_TWS", "OA-TEMP", "Outside Air Temperature"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 70.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BD "730_TWS", "--TWR1--", "------------------------"
    GRAPHICS 0, 0
    UNITS "------", "-----"
    INIT N, N, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

CS "730_TWS", "CT1-STPT", "CS MODEL - Working Stpt"
    MODEL "730_TWR"
~This Model not found in Model Database.
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "AD_6", "AD_6"
    FORMAT 1

AOS "730_TWS", "CT1-CHLR", "CT-1 Chiller Setpoint"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO1", N
    INIT 65.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AOS "730_TWS", "CT1-HEX", "CT-1 HEX Setpoint"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO2", N
    INIT 40.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AD "730_TWS", "T1B-CDWS", "CT-1 Bypass CDW Sup Temp"
    ASSOCINP "CS", "NC-43HW", "DX41X101", "AI_1"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 60.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AD "730_TWS", "T1C-CDWS", "CT-1 Chlr CDW Sup Temp"
    ASSOCINP "AI", "730_C1", "CDWS1-T", "VALUE"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 70.00000
    ALARMSET 1.000000, , , 32.00000, 95.00000, 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AD "730_TWS", "T1H-CDWS", "CT-1 HEX CDW Sup Temp"
    ASSOCINP "AI", "730_HXS", "HX1-CDWS", "VALUE"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 70.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "730_TWS", "CT1B-CMD", "Clg Twr-1 Bypass Control"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "XT2AO7", Y
    INIT 0.0, Y, N
    UNITS "% Byp", 1
    REPORT N, Y, N, N, 0

BO "730_TWS", "CT1F-SS", "Clg Twr-1 VFD Sta/Sto"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DO7", Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

AOS "730_TWS", "CT1F-CMD", "Clg Twr-1 VFD Control"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "XT2AO8", Y
    INIT 0.0, Y, N
    UNITS "%Speed", 1
    REPORT N, Y, N, N, 0

BD "730_TWS", "--TWR2--", "------------------------"
    GRAPHICS 0, 0
    UNITS "------", "-----"
    INIT N, N, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

CS "730_TWS", "CT2-STPT", "CS MODEL - Working Stpt"
    MODEL "730_TWR"
~This Model not found in Model Database.
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "AD_6", "AD_6"
    FORMAT 1

AOS "730_TWS", "CT2-CHLR", "CT-2 Chiller Setpoint"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO1", N
    INIT 65.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AD "730_TWS", "T2C-CDWS", "CT-2 Chlr CDW Sup Temp"
    ASSOCINP "AI", "730_C2", "CDWS2-T", "VALUE"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 70.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "730_TWS", "CT2B-CMD", "Clg Twr-2 Bypass Control"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "XT1AO7", Y
    INIT 0.0, Y, N
    UNITS "% Byp", 1
    REPORT N, Y, N, N, 0

BO "730_TWS", "CT2F-SS", "Clg Twr-2 VFD Sta/Sto"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DO7", Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

AOS "730_TWS", "CT2F-CMD", "Clg Twr-2 VFD Control"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "XT1AO8", Y
    INIT 0.0, Y, N
    UNITS "%Speed", 1
    REPORT N, Y, N, N, 0

BD "730_TWS", "--TWR3--", "------------------------"
    GRAPHICS 0, 0
    UNITS "------", "-----"
    INIT N, N, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

CS "730_TWS", "CT3-STPT", "CS MODEL - Working Stpt"
    MODEL "730_TWR"
~This Model not found in Model Database.
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "AD_6", "AD_6"
    FORMAT 1

AOS "730_TWS", "CT3-CHLR", "CT-3 Chiller Setpoint"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO1", N
    INIT 70.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AOS "730_TWS", "CT3-HEX", "CT-3 HEX Setpoint"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO2", N
    INIT 40.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AD "730_TWS", "T3F-CDWS", "CT-3 VFD CDW Sup Temp"
    ASSOCINP "CS", "NC-43HW", "DX43X104", "AI_1"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 70.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AD "730_TWS", "T3C-CDWS", "CT-3 Chlr CDW Sup Temp"
    ASSOCINP "AI", "730_C3", "CDWS3-T", "VALUE"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 70.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AD "730_TWS", "T3H-CDWS", "CT-3 HEX CDW Sup Temp"
    ASSOCINP "AD", "730_HXS", "HX2-CDWS", "VALUE"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 70.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "730_TWS", "CT3B-CMD", "CT-3 Bypass Control"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "OUT2", Y
    INIT 0.0, N, N
    UNITS "% Byp", 1
    REPORT N, Y, N, N, 5

BO "730_TWS", "CT3F-SS", "Clg Twr-3 VFD Sta/Sto"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DO7", Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

AOS "730_TWS", "CT3F-CMD", "Clg Twr-3 VFD Control"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "XT2AO7", Y
    INIT 0.0, Y, N
    UNITS "%Speed", 1
    REPORT N, Y, N, N, 0

CS "730_B-3", "ALL-PNTS", "CS MODEL - Zone Setpoint"
    MODEL "UpRTOP_C"
~This Model not found in Model Database.
    HARDWARE "NC-43HW", "730_B-3"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 1

BO "730_B-3", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_B-3"
    GRAPHICS 0, 0
    N2OPENHW "BD", 229, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_B-3", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_B-3"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER
    FEEDBACK "730_B-3", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_B-3", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_B-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_B-3", "FAILURE", "Unit Sequence Failure"
    ASSOCINP "CS", "730_B-3", "ALL-PNTS", "BD_11"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 13, 6, 2, 5

BD "730_B-3", "OFF-NORM", "Unit Off Normal"
    ASSOCINP "CS", "730_B-3", "ALL-PNTS", "BD_13"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 11, 6, 2, 5

BD "730_B-3", "HI-TEMP", "Unit Zone High Temp"
    ASSOCINP "CS", "730_B-3", "ALL-PNTS", "BD_12"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 12, 6, 2, 5

AI "730_B-3", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_B-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AI "730_B-3", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_B-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, , , 65.00000, 85.00000, 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

AI "730_B-3", "RA-TEMP", "Return Air Temp"
    HARDWARE "NC-43HW", "730_B-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "730_B-3", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_B-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_B-3", "WTR-DET", "Water Detection Status"
    HARDWARE "NC-43HW", "730_B-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 6, 6, 2, 5

AOS "730_B-3", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_B-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

CS "730_B-2", "ALL-PNTS", "CS MODEL - Zone Setpoint"
    MODEL "UpRTOP_C"
~This Model not found in Model Database.
    HARDWARE "NC-43HW", "730_B-2"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 1

BO "730_B-2", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_B-2"
    GRAPHICS 0, 0
    N2OPENHW "BD", 229, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_B-2", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_B-2"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER
    FEEDBACK "730_B-2", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_B-2", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_B-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_B-2", "FAILURE", "Unit Sequence Failure"
    ASSOCINP "CS", "730_B-2", "ALL-PNTS", "BD_11"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 13, 6, 2, 5

BD "730_B-2", "OFF-NORM", "Unit Off Normal"
    ASSOCINP "CS", "730_B-2", "ALL-PNTS", "BD_13"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 11, 6, 2, 5

BD "730_B-2", "HI-TEMP", "Unit Zone High Temp"
    ASSOCINP "CS", "730_B-2", "ALL-PNTS", "BD_12"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 12, 6, 2, 5

AI "730_B-2", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_B-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AI "730_B-2", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_B-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, , , 65.00000, 85.00000, 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

AI "730_B-2", "RA-TEMP", "Return Air Temp"
    HARDWARE "NC-43HW", "730_B-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "730_B-2", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_B-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_B-2", "WTR-DET", "Water Detection Status"
    HARDWARE "NC-43HW", "730_B-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 6, 6, 2, 5

AOS "730_B-2", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_B-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

AI "730_3-4", "OA-TEMP", "Outside Air Temperature"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 1
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BO "730_3-4", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_3-4", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER
    FEEDBACK "730_3-4", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "730_3-4", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 0

AOS "730_3-4", "DA_Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_3-4", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 0.1000000, , , 40.00000, , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

CS "730_3-4", "CLGV-CMD", "Cooling Valve Command"
    MODEL "UNT-AO_2"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "AO_1", "AO_1"
    FORMAT 1

AOS "730_3-4", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 237, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_3-4", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 76.00000, 10.00000, 65.00000, 90.00000, 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AOS "730_3-4", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "AO", 4, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BD "730_3-4", "MA-LOW", "Mixed Air Temp Low"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_3-4", "DA-LOW", "Discharge Air Temp Low"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

AI "730_3-4", "MA-TEMP", "Mixed Air Temperature"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 0, 3, 2, 0

AOS "730_3-4", "RACO2-SP", "Return Air CO2 Setpoint"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 153, N
    INIT 900.0000, Y, Y
    UNITS "PPM", 0
    REPORT N, Y, N, N, 5

AI "730_3-4", "RA-CO2", "Return Air CO2 Reading"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "PPM", 0
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "730_3-4", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_3-4", "Econ", "   Economizer Disabled"
    GRAPHICS 0, 0
    UNITS ".", "Dis"
    INIT N, Y, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

AOS "730_3-4", "DMP-CMD", "Damper Command"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "AO", 3, Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 0

BI "730_3-4", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 15, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

CS "730_3-4", "ALL-PNTS", "CS MODEL - Act Dis Stpt"
    MODEL "U_MASPcC"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

JCB "730_3-4", "DA_LOW"

AI "730_3-4", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V3-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "%", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_3-4", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V3-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 0

AI "730_3-4", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-43HW", "730_V3-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_3-4", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-43HW", "730_V3-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "730_3-4", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 0.0
    ALARMSET , , , , , 1, N
    REPORT N, Y, Y, N, , , 0, 0, 0, 0

JCB "730_3-4", "KW-VFD"

AI "730_3-3", "OA-TEMP", "Outside Air Temperature"
    HARDWARE "NC-43HW", "730_3-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 1
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BO "730_3-3", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_3-3"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_3-3", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_3-3"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER
    FEEDBACK "730_3-3", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "730_3-3", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_3-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_3-3", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-43HW", "730_3-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_3-3", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_3-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 1.000000, , , 40.00000, 85.00000, 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

CS "730_3-3", "CLGV-CMD", "Cooling Valve Command"
    MODEL "UNT-AO_2"
    HARDWARE "NC-43HW", "730_3-3"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "AO_1", "AO_1"
    FORMAT 1

AOS "730_3-3", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-43HW", "730_3-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_3-3", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_3-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 76.00000, 10.00000, 65.00000, 88.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "730_3-3", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-43HW", "730_3-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BD "730_3-3", "MA-LOW", "Mixed Air Temp Low"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_3-3", "DA-LOW", "Discharge Air Temp Low"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

AI "730_3-3", "Z-HUMD", "Zone Humidity"
    HARDWARE "NC-43HW", "730_3-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "% RH", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AI "730_3-3", "MA-TEMP", "Mixed Air Temperature"
    HARDWARE "NC-43HW", "730_3-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "730_3-3", "RACO2-SP", "Return Air CO2 Setpoint"
    HARDWARE "NC-43HW", "730_3-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 153, N
    INIT 900.0000, Y, Y
    UNITS "PPM", 0
    REPORT N, Y, N, N, 5

AI "730_3-3", "RA-CO2", "Return Air CO2 Reading"
    HARDWARE "NC-43HW", "730_3-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "PPM", 0
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "730_3-3", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_3-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_3-3", "Econ", "   Economizer Disabled"
    GRAPHICS 0, 0
    UNITS ".", "Dis"
    INIT N, Y, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

AOS "730_3-3", "DMP-CMD", "Damper Command"
    HARDWARE "NC-43HW", "730_3-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 3, Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

BI "730_3-3", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_3-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 15, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

CS "730_3-3", "ALL-PNTS", "CS MODEL - Act Dis Stpt"
    MODEL "U_MASPcC"
    HARDWARE "NC-43HW", "730_3-3"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

JCB "730_3-3", "DA_LOW"

JCB "730_3-3", "vfd_spd"

JCB "730_3-3", "stpt"

AI "730_3-3", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V3-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "%", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_3-3", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V3-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 0

AI "730_3-3", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-43HW", "730_V3-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_3-3", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-43HW", "730_V3-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "730_3-3", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 0.0
    ALARMSET , , , , , 1, N
    REPORT N, Y, Y, N, , , 0, 0, 0, 0

JCB "730_3-3", "KW-VFD"

AOS "730_6-3N", "OA-TEMP", "Outside Air Temperature"
    HARDWARE "NC-43HW", "730_6-3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO7", N
    INIT 70.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AOS "730_6-3N", "MCLG-STP", "Mechanical Clg OA Stpt"
    HARDWARE "NC-43HW", "730_6-3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO5", N
    INIT -28.00000, Y, Y
    UNITS ">Deg F", 1
    REPORT N, Y, N, N, 5

BO "730_6-3N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_6-3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO1", N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_6-3N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_6-3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DO3", Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER 5, 1, 0, 255
    FEEDBACK "730_6-3N", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "730_6-3N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_6-3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI1"
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

AOS "730_6-3N", "DA-STPT", "Discharge Air Setpoint"
    HARDWARE "NC-43HW", "730_6-3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO1", N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_6-3N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_6-3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI3"
    UNITS "Deg F", 1
    ALARMSET 1.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2,

BD "730_6-3N", "Econ", "   Economizer Disabled"
    GRAPHICS 0, 0
    UNITS ".", "Dis"
    INIT N, Y, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

AOS "730_6-3N", "DMP-CMD", "Damper Command"
    HARDWARE "NC-43HW", "730_6-3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "OUT1", Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

AOS "730_6-3N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_6-3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "OUT2", Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

AOS "730_6-3N", "Z-STPT", "Zone Setpoint"
    HARDWARE "NC-43HW", "730_6-3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO2", N
    INIT 78.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "730_6-3N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_6-3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI4"
    UNITS "Deg F", 1
    ALARMSET 1.000000, 78.00000, 10.00000, 65.00000, 85.00000, 1
    REPORT N, Y, N, N, 0, 0, 0, 2, 2,

AOS "730_6-3N", "SUP-VFD", "Sup Fan VFD Cmd 30% Min"
    HARDWARE "NC-43HW", "730_6-3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "OUT9", Y
    INIT 0.0, N, N
    UNITS "% Cmd", 1
    REPORT N, Y, N, N, 5

AI "730_6-3N", "MA-TEMP", "Mixed Air Temperature"
    HARDWARE "NC-43HW", "730_6-3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI2"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

CS "730_6-3N", "RACO2-SP", "Return Air CO2 Setpoint"
    MODEL "730CO2SP"
~This Model not found in Model Database.
    HARDWARE "NC-43HW", "730_6-3"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 0

AI "730_6-3N", "RA-CO2", "Return Air CO2 Reading"
    HARDWARE "NC-43HW", "730_6-3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI5"
    UNITS "PPM", 0
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

BI "730_6-3N", "WTR-DET", "Floor Water Detector"
    HARDWARE "NC-43HW", "730_6-3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI4"
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 11, 0, 2,

BI "730_6-3N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_6-3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI2"
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0,

BI "730_6-3N", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_6-3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI3"
    INIT N, 1, 15, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2,

AI "730_6-3N", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V6-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "%", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_6-3N", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V6-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AI "730_6-3N", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-43HW", "730_V6-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_6-3N", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-43HW", "730_V6-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "730_6-3N", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "730_6-3N", "KW-VFD"

AOS "730_6-1N", "OA-TEMP", "Outside Air Temperature"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO7", N
    INIT 70.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AOS "730_6-1N", "MCLG-STP", "Mechanical Clg OA Stpt"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO5", N
    INIT -28.00000, Y, Y
    UNITS ">Deg F", 1
    REPORT N, Y, N, N, 5

BO "730_6-1N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO1", N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_6-1N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DO3", Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER 5, 1, 0, 255
    FEEDBACK "730_6-1N", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "730_6-1N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI1"
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

AOS "730_6-1N", "DA-STPT", "Discharge Air Setpoint"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO1", N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_6-1N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI3"
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2,

BD "730_6-1N", "Econ", "   Economizer Disabled"
    GRAPHICS 0, 0
    UNITS ".", "Dis"
    INIT N, Y, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

AOS "730_6-1N", "DMP-CMD", "Damper Command"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "OUT1", Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

AOS "730_6-1N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "OUT2", Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

AOS "730_6-1N", "Z-STPT", "Zone Setpoint"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO2", N
    INIT 78.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "730_6-1N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI4"
    UNITS "Deg F", 1
    ALARMSET 1.000000, 78.00000, 10.00000, 55.00000, 85.00000, 1
    REPORT N, Y, N, N, 0, 0, 0, 2, 2,

AOS "730_6-1N", "SUP-VFD", "Sup Fan VFD Cmd 30% Min "
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "OUT9", Y
    INIT 0.0, N, N
    UNITS "% Cmd", 1
    REPORT N, Y, N, N, 5

AI "730_6-1N", "Z-HUMD", "Zone Humidity"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI7"
    UNITS "% RH", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

AI "730_6-1N", "MA-TEMP", "Mixed Air Temperature"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI2"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

CS "730_6-1N", "RACO2-SP", "Return Air CO2 Setpoint"
    MODEL "730CO2SP"
~This Model not found in Model Database.
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 0

AI "730_6-1N", "RA-CO2", "Return Air CO2 Reading"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI5"
    UNITS "PPM", 0
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

BI "730_6-1N", "WTR-DET", "Floor Water Detector"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI4"
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 11, 0, 2,

BI "730_6-1N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI2"
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0,

BI "730_6-1N", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI3"
    INIT N, 1, 15, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2,

AI "730_6-1N", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V6-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "%", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_6-1N", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V6-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AI "730_6-1N", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-43HW", "730_V6-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_6-1N", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-43HW", "730_V6-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "730_6-1N", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "730_6-1N", "vfd_spd"

JCB "730_6-1N", "stpt"

JCB "730_6-1N", "KW-VFD"

AOS "730_6-2N", "OA-TEMP", "Outside Air Temperature"
    HARDWARE "NC-43HW", "730_6-2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO7", N
    INIT 70.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AOS "730_6-2N", "MCLG-STP", "Mechanical Clg OA Stpt"
    HARDWARE "NC-43HW", "730_6-2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO5", N
    INIT -28.00000, Y, Y
    UNITS ">Deg F", 1
    REPORT N, Y, N, N, 5

BO "730_6-2N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_6-2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO1", N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_6-2N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_6-2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DO3", Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER 5, 1, 0, 255
    FEEDBACK "730_6-2N", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "730_6-2N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_6-2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI1"
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

AOS "730_6-2N", "DA-STPT", "Discharge Air Setpoint"
    HARDWARE "NC-43HW", "730_6-2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO1", N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "730_6-2N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_6-2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI3"
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , , 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2,

BD "730_6-2N", "Econ", "   Economizer Disabled"
    GRAPHICS 0, 0
    UNITS ".", "Dis"
    INIT N, Y, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

AOS "730_6-2N", "DMP-CMD", "Damper Command"
    HARDWARE "NC-43HW", "730_6-2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "OUT1", Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

AOS "730_6-2N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_6-2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "OUT2", Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

AOS "730_6-2N", "Z-STPT", "Zone Setpoint"
    HARDWARE "NC-43HW", "730_6-2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO2", N
    INIT 78.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "730_6-2N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_6-2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI4"
    UNITS "Deg F", 1
    ALARMSET 1.000000, 78.00000, 10.00000, 65.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2,

AOS "730_6-2N", "SUP-VFD", "Sup Fan VFD Cmd 30% Min"
    HARDWARE "NC-43HW", "730_6-2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "OUT9", Y
    INIT 0.0, N, N
    UNITS "% Cmd", 1
    REPORT N, Y, N, N, 5

AI "730_6-2N", "MA-TEMP", "Mixed Air Temperature"
    HARDWARE "NC-43HW", "730_6-2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI2"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

CS "730_6-2N", "RACO2-SP", "Return Air CO2 Setpoint"
    MODEL "730CO2SP"
~This Model not found in Model Database.
    HARDWARE "NC-43HW", "730_6-2"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 0

AI "730_6-2N", "RA-CO2", "Return Air CO2 Reading"
    HARDWARE "NC-43HW", "730_6-2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI5"
    UNITS "PPM", 0
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

BI "730_6-2N", "WTR-DET", "Floor Water Detector"
    HARDWARE "NC-43HW", "730_6-2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI4"
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 11, 0, 2,

BI "730_6-2N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_6-2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI2"
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0,

BI "730_6-2N", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_6-2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI3"
    INIT N, 1, 15, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2,

AI "730_6-2N", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V6-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "%", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_6-2N", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V6-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AI "730_6-2N", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-43HW", "730_V6-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_6-2N", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-43HW", "730_V6-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "730_6-2N", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "730_6-2N", "KW-VFD"

AOS "730_6FL", "STC-STPT", "Static Pressure Setpoint"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO8", N
    INIT 5.000000e-002, Y, Y
    UNITS "Inwc", 3
    REPORT N, Y, N, N, 5

AI "730_6FL", "STATIC", "Static Pressure"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI8"
    UNITS "Inwc", 3
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

AOS "730_6FL", "RELD-CMD", "Relief Damper Command"
    HARDWARE "NC-43HW", "730_6-1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "OUT10", Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

BO "730_HXS", "HEX-RST", "FMS Reset of HEX Alarms"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO14", N
    UNITS "Off", "Reset", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

AD "730_HXS", "OA-TEMP", "Outside Air Temperature"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 70.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "730_HXS", "OA-LL", "HEX OA Low Limit to Ena"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO7", N
    INIT -10.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AOS "730_HXS", "CDWR-LL", "HEX CDWR Low Limit to Sw"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO5", N
    INIT 50.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AOS "730_HXS", "CHWR-HLL", "HEX CHWR Hi Lim Lag Chlr"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO4", N
    INIT 60.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AOS "730_HXS", "CHWR-HLF", "HEX CHWR High Limit Fail"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO6", N
    INIT 62.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

BO "730_HXS", "ENA-HEX", "Enable HEX Auto Switch"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO8", N
    UNITS "No", "Yes", N, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_HXS", "HEX-ENA", "HEX Enabled by OA-Temp"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS11"
    INIT N, 0, 30, N
    UNITS "No", "Yes"
    REPORT N, Y, N, N, , 0, 0,

BI "730_HXS", "HEX-SW", "HEX Open IsoV & CDWPmps"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS12"
    INIT N, 0, 30, N
    UNITS "No", "Yes"
    REPORT N, Y, N, N, , 0, 0,

BI "730_HXS", "HEX-RDY", "HEX Ready Start CHWPmps"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS13"
    INIT N, 0, 30, N
    UNITS "No", "Yes"
    REPORT N, Y, N, N, , 0, 0,

BI "730_HXS", "HEX-C2Lg", "HEX CHWR High - Run C#2"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS19"
    INIT N, 0, 30, N
    UNITS "No", "Yes"
    REPORT N, Y, N, N, , 0, 0,

BI "730_HXS", "HEX-FAIL", "HEX CHWR High Temp"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS14"
    INIT N, 1, 30, N
    UNITS "No", "Yes"
    REPORT N, Y, N, N, 0, 6, 2,

BO "730_HXS", "ISOV-C", "Isolation Valves Cmd"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DO6", Y
    UNITS "Chlr", "HEX", N, Y, N
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_HXS", "-", " HEX Common Temperatures"
    GRAPHICS 0, 0
    UNITS "------", "-----"
    INIT N, N, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

AD "730_HXS", "HX-CCHWS", "HEX Common CHW Sup Temp"
    ASSOCINP "CS", "NC-43HW", "DX43X103", "AD_3"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 77.70000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AD "730_HXS", "HX-CCHWR", "HEX Common CHW Ret Temp"
    ASSOCINP "CS", "NC-43HW", "DX43X103", "AD_4"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 77.70000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AD "730_HXS", "HX-CCDWS", "HEX Common CDW Sup Temp"
    ASSOCINP "CS", "NC-43HW", "DX43X103", "AD_5"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 77.70000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AD "730_HXS", "HX-CCDWR", "HEX Common CDW Ret Temp"
    ASSOCINP "CS", "NC-43HW", "DX43X103", "AD_6"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 77.70000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BD "730_HXS", "--", "   HEX-1 Temperatures"
    GRAPHICS 0, 0
    UNITS "------", "-----"
    INIT N, N, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

AI "730_HXS", "HX1-CHWS", "HEX1 Chil Wtr Sup Temp"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI5"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

AI "730_HXS", "HX1-CHWR", "HEX1 Chil Wtr Ret Temp"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI6"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

AI "730_HXS", "HX1-CDWS", "HEX1 Cond Wtr Sup Temp"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI7"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

AI "730_HXS", "HX1-CDWR", "HEX1 Cond Wtr Ret Temp"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI8"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

BD "730_HXS", "---", "   HEX-2 Temperatures"
    GRAPHICS 0, 0
    UNITS "------", "-----"
    INIT N, N, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

AD "730_HXS", "HX2-CHWS", "HEX2 Chil Wtr Sup Temp"
    ASSOCINP "CS", "NC-43HW", "DX43X103", "AI_1"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AD "730_HXS", "HX2-CHWR", "HEX2 Chil Wtr Ret Temp"
    ASSOCINP "CS", "NC-43HW", "DX43X103", "AI_2"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AD "730_HXS", "HX2-CDWS", "HEX2 Cond Wtr Sup Temp"
    ASSOCINP "CS", "NC-43HW", "DX43X103", "AI_3"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AD "730_HXS", "HX2-CDWR", "HEX2 Cond Wtr Ret Temp"
    ASSOCINP "CS", "NC-43HW", "DX43X103", "AI_4"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "730_C1", "OA-TEMP", "Outside Air Temperature"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO8", N
    INIT 70.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

BO "730_C1", "C1-LEAD", "Chiller-1 Lead Unit"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO1", N
    UNITS "No", "Yes", N, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_C1", "RUN-LEAD", "Chiller-1 Run as Lead"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO17", N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_C1", "C1-LAG", "Chiller-1 Lag Unit"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO2", N
    UNITS "No", "Yes", Y, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_C1", "RUN-LAG", "Chiller-1 Run as Lag"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO18", N
    UNITS "No", "Yes", Y, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_C1", "C1-SBY", "Chiller-1 Standby Unit"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO3", N
    UNITS "No", "Yes", N, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_C1", "RUN-SBY", "Chiller-1 Run as Standby"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS10"
    INIT N, 0, 30, N
    UNITS "No", "Yes"
    REPORT N, Y, N, N, , 0, 0,

BO "730_C1", "C1-OVD", "Chiller-1 Override On"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO5", N
    UNITS "Off", "**On**", N, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_C1", "C1-USE", "Chiller-1 In Service Cmd"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO4", N
    UNITS "No!!!", "Yes", Y, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

CS "730_C1", "ALL-PNTS", "CS MODEL - Chiller-1 Cmd"
    MODEL "730_CH1"
~This Model not found in Model Database.
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "BD_13", "BD_13"
    FORMAT 1

BO "730_C1", "C1-C", "Chiller-1 Enable Cmd"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DO3", Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER 5, 1, 0, 255
    FEEDBACK "730_C1", "C1-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_C1", "C1-STS", "Chiller-1 Status"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI1"
    INIT N, 2, 255, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

BI "730_C1", "C1-ALM", "Chiller-1 Safeties"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI2"
    INIT N, 1, 30, N
    UNITS "Normal", "Alm!!!"
    REPORT N, Y, N, N, , 0, 0,

BI "730_C1", "C1-XOK", "Chiller-1 Seq Failure"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS3"
    INIT N, 1, 30, N
    UNITS "No", "Yes!!!"
    REPORT N, Y, N, N, 1, 6, 2,

BI "730_C1", "C1-OFN", "Chiller-1 Off Normal"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS1"
    INIT N, 1, 30, N
    UNITS "No", "Yes!!!"
    REPORT N, Y, N, N, , 0, 0,

BI "730_C1", "C1-HIT", "Chiller-1 High Temp"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS2"
    INIT N, 1, 30, N
    UNITS "No", "Yes!!!"
    REPORT N, Y, N, N, , 0, 0,

BI "730_C1", "PMPS-OFN", "Chiller-1 Pumps Off Norm"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS4"
    INIT N, 1, 30, N
    UNITS "No", "Yes!!!"
    REPORT N, Y, N, N, , 0, 0,

BI "730_C1", "CHWP1-HX", "CHWP-1 Run for HEX"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS15"
    INIT N, 0, 30, N
    UNITS "No", "Yes"
    REPORT N, Y, N, N, , 0, 0,

BO "730_C1", "CHWP1-C", "Chil Wtr Pump-1 Cmd"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DO4", Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER 5, 1, 0, 255
    FEEDBACK "730_C1", "CHWP1-S", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_C1", "CHWP1-S", "Chil Wtr Pump-1 Status"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI3"
    INIT N, 2, 60, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

BD "730_C1", "CDW-PUMP", "Schedule Water Treatment"
    GRAPHICS 0, 0
    UNITS "Off", "!!On!!"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 0

BD "730_C1", "CDWP4-HX", "CDWP-4 Run for HEX"
    ASSOCINP "BI", "730_C3", "CDWP6-HX", "VALUE"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_C1", "CDWP4-C", "Cond Wtr Pump-4 Cmd"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DO5", Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER 5, 1, 0, 255
    FEEDBACK "730_C1", "CDWP4-S", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_C1", "CDWP4-S", "Cond Wtr Pump-4 Status"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI4"
    INIT N, 2, 60, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

AOS "730_C1", "CHWS-HL", "Chil Wtr Sup High Limit"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO3", N
    INIT 59.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "730_C1", "CHWS1-T", "Chlr-1 Chil Wtr Sup Temp"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI1"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

AI "730_C1", "CHWR1-T", "Chlr-1 Chil Wtr Ret Temp"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI2"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

AI "730_C1", "CDWS1-T", "Chlr-1 Cond Wtr Sup Temp"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI3"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

AI "730_C1", "CDWR1-T", "Chlr-1 Cond Wtr Ret Temp"
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI4"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

JCB "730_C1", "CDW_PUMP"

CS "730_C1", "ChRstPul", "CS Model - Chlr Rst Puls"
    MODEL "730_CH1b"
~This Model not found in Model Database.
    HARDWARE "NC-43HW", "730_CH1"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "BD_1", "BD_1"
    FORMAT 1

AOS "730_C2", "OA-TEMP", "Outside Air Temperature"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO8", N
    INIT 70.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

BO "730_C2", "C2-LEAD", "Chiller-2 Lead Unit"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO1", N
    UNITS "No", "Yes", Y, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_C2", "RUN-LEAD", "Chiller-2 Run as Lead"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO17", N
    UNITS "No", "Yes", Y, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_C2", "C2-LAG", "Chiller-2 Lag Unit"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO2", N
    UNITS "No", "Yes", N, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_C2", "RUN-LAG", "Chiller-2 Run as Lag"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO18", N
    UNITS "No", "Yes", N, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_C2", "RUN-LAG2", "Chiller-2 Run as HEX Lag"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO14", N
    UNITS "No", "Yes", N, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_C2", "C2-SBY", "Chiller-2 Standby Unit"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO3", N
    UNITS "No", "Yes", N, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_C2", "RUN-SBY", "Chiller-2 Run as Standby"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS10"
    INIT N, 0, 30, N
    UNITS "No", "Yes"
    REPORT N, Y, N, N, , 0, 0,

BO "730_C2", "C2-OVD", "Chiller-2 Override On"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO5", N
    UNITS "Off", "**On**", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_C2", "C2-USE", "Chiller-2 In Service Cmd"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO4", N
    UNITS "No!!!", "Yes", Y, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

CS "730_C2", "ALL-PNTS", "CS MODEL - Chiller-2 Cmd"
    MODEL "730_CH2"
~This Model not found in Model Database.
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "BD_14", "BD_14"
    FORMAT 1

BO "730_C2", "C2-C", "Chiller-2 Enable Cmd"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DO3", Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER 5, 1, 0, 255
    FEEDBACK "730_C2", "C2-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_C2", "C2-STS", "Chiller-2 Status"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI1"
    INIT N, 1, 255, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

BI "730_C2", "C2-ALM", "Chiller-2 Safeties"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI2"
    INIT N, 1, 30, N
    UNITS "Normal", "Alm!!!"
    REPORT N, Y, N, N, , 0, 0,

BI "730_C2", "C2-XOK", "Chiller-2 Seq Failure"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS3"
    INIT N, 1, 30, N
    UNITS "No", "Yes!!!"
    REPORT N, Y, N, N, 2, 6, 2,

BI "730_C2", "C2-OFN", "Chiller-2 Off Normal"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS1"
    INIT N, 1, 30, N
    UNITS "No", "Yes!!!"
    REPORT N, Y, N, N, , 0, 0,

BI "730_C2", "C2-HIT", "Chiller-2 High Temp"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS2"
    INIT N, 1, 30, N
    UNITS "No", "Yes!!!"
    REPORT N, Y, N, N, , 0, 0,

BI "730_C2", "PMPS-OFN", "Chiller-2 Pumps Off Norm"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS4"
    INIT N, 1, 30, N
    UNITS "No", "Yes!!!"
    REPORT N, Y, N, N, , 0, 0,

BI "730_C2", "CHWP2-S", "Chil Wtr Pump-2 Status"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI3"
    INIT N, 0, 60, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

BD "730_C2", "CDW-PUMP", "Schedule Water Treatment"
    GRAPHICS 0, 0
    UNITS "Off", "!!On!!"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_C2", "CDWP5-C", "Cond Wtr Pump-5 Cmd"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DO6", Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER 5, 1, 0, 255
    FEEDBACK "730_C2", "CDWP5-S", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_C2", "CDWP5-S", "Cond Wtr Pump-5 Status"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI4"
    INIT N, 1, 60, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

AOS "730_C2", "CHWS-HL", "Chil Wtr Sup High Limit"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO3", N
    INIT 59.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "730_C2", "CHWS2-T", "Chlr-2 Chil Wtr Sup Temp"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI1"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

AI "730_C2", "CHWR2-T", "Chlr-2 Chil Wtr Ret Temp"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI2"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

AI "730_C2", "CDWS2-T", "Chlr-2 Cond Wtr Sup Temp"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI3"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

AI "730_C2", "CDWR2-T", "Chlr-2 Cond Wtr Ret Temp"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI4"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

JCB "730_C2", "CDW_PUMP"

BO "730_CHS", "CHL-RST", "FMS Reset of Chlr Alarms"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO12", N
    UNITS "Off", "Reset", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

AD "730_CHS", "OA-TEMP", "Outside Air Temperature"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 64.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BO "730_CHS", "WIN-LEAD", "Winter Chlr-2 Lead Cmd"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO13", N
    UNITS "No", "Yes", Y, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_CHS", "ENA-CLG", "Enable Mechanical Clg"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO6", N
    UNITS "No", "Yes", Y, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_CHS", "MECH-CLG", "Mechanical Cooling"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO7", N
    UNITS "No", "Yes", Y, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

AD "730_CHS", "OAHL-LAG", "OA Hi Limit for Lag Chlr"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 70.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, , , 0, 0, 0, 5

JCB "730_CHS", "SHARE"

JCB "730_CHS", "CHL_RST"

JCB "730_CHS", "RUN_LEAD"

AD "730_CHS", "OAHLDiff", "OA Hi Limit Diff for Lag"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 3.000000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, , , 0, 0, 0, 5

BD "730_CHS", "OA-Lag", "OA High Lag Chlr Needed"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

AD "730_CHS", "LEADCHWS", "Lead Chiller CHWS Temp"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 45.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, , , 0, 0, 0, 5

AD "730_CHS", "CHWHLLAG", "CHWS Hi Lim for Lag Chlr"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 47.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, , , 0, 0, 0, 5

AD "730_CHS", "CHWHLDif", "CHWS Hi Lim Diff for Lag"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 3.000000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, , , 0, 0, 0, 5

BD "730_CHS", "CHWS-Lag", "CHWS Hi Lag Chlr Needed"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_CHS", "Sby-Lag", "Sby Fail Lag Chlr Needed"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_CHS", "-", "(Building Mode Control) "
    GRAPHICS 0, 0
    UNITS "------", "-----"
    INIT N, N, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

AD "730_CHS", "MODE-Sw", "Summer/Winter Mode Stpt"
    GRAPHICS 0, 0
    UNITS "<Deg F", 1, 65.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, , , 0, 0, 0, 5

AD "730_CHS", "MODE-Dif", "Summer/Winter Mode Diff"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 2.000000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, , , 0, 0, 0, 5

BD "730_CHS", "MODE-Sts", "Summer/Winter Mode Sts"
    GRAPHICS 0, 0
    UNITS "SMODE", "WMODE"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_CHS", "--", "  (One needs to be On) "
    GRAPHICS 0, 0
    UNITS "------", "-----"
    INIT N, N, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

BD "730_CHS", "SMODE-1", "C1-Lead, C2-Lag, C3-Sby"
    GRAPHICS 0, 0
    UNITS "Off", "On!!!!"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_CHS", "SMODE-2", "C1-Lead, C3-Lag, C2-Sby"
    GRAPHICS 0, 0
    UNITS "Off", "On!!!!"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_CHS", "SMODE-3", "C2-Lead, C1-Lag, C3-Sby"
    GRAPHICS 0, 0
    UNITS "Off", "On!!!!"
    INIT N, Y, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_CHS", "SMODE-4", "C2-Lead, C3-Lag, C1-Sby"
    GRAPHICS 0, 0
    UNITS "Off", "On!!!!"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_CHS", "SMODE-5", "C3-Lead, C1-Lag, C2-Sby"
    GRAPHICS 0, 0
    UNITS "Off", "On!!!!"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_CHS", "SMODE-6", "C3-Lead, C2-Lag, C1-Sby"
    GRAPHICS 0, 0
    UNITS "Off", "On!!!!"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_CHS", "---", "  (One needs to be On) "
    GRAPHICS 0, 0
    UNITS "------", "-----"
    INIT N, N, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

BD "730_CHS", "WMODE-1", "C2-Lead, C1-Lag, C3-Sby"
    GRAPHICS 0, 0
    UNITS "Off", "On!!!!"
    INIT N, Y, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "730_CHS", "WMODE-2", "C2-Lead, C3-Lag, C1-Sby"
    GRAPHICS 0, 0
    UNITS "Off", "On!!!!"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

JCB "730_CHS", "RUN_LAG"

JCB "730_CHS", "MECH_CLG"

JCB "730_CHS", "C2_LEAD"

JCB "730_CHS", "MODES"

JCB "730_CHS", "MODE_Sw"

AD "730_PH1N", "OA-TEMP", "Outside Air Temperature"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 77.70000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BO "730_PH1N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_PH1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_PH1N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_PH1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_PH1N", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_PH1N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_PH1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_PH1N", "DA-STPT", "Discharge Air Setpoint"
    HARDWARE "NC-43HW", "730_PH1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 129, N
    INIT 60.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "730_PH1N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_PH1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AI "730_PH1N", "RA-TEMP", "Return Air Temp"
    HARDWARE "NC-43HW", "730_PH1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "Deg F", 1
    ALARMSET 1.000000, , , 45.00000, 90.00000, 1
    REPORT N, Y, N, N, , , 6, 0, 0, 5

AI "730_PH1N", "MA-TEMP", "Mixed Air Temperature"
    HARDWARE "NC-43HW", "730_PH1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "730_PH1N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_PH1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_PH1N", "DMP-CMD", "Damper Command"
    HARDWARE "NC-43HW", "730_PH1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

AOS "730_PH1N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_PH1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "730_C3", "OA-TEMP", "Outside Air Temperature"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO8", N
    INIT 70.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

BO "730_C3", "C3-LEAD", "Chiller-3 Lead Unit"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO1", N
    UNITS "No", "Yes", N, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_C3", "RUN-LEAD", "Chiller-3 Run as Lead"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO17", N
    UNITS "No", "Yes", N, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_C3", "C3-LAG", "Chiller-3 Lag Unit"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO2", N
    UNITS "No", "Yes", N, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_C3", "RUN-LAG", "Chiller-3 Run as Lag"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO18", N
    UNITS "No", "Yes", N, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_C3", "C3-SBY", "Chiller-3 Standby Unit"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO3", N
    UNITS "No", "Yes", Y, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_C3", "RUN-SBY", "Chiller-3 Run as Standby"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS17"
    INIT N, 0, 30, N
    UNITS "No", "Yes"
    REPORT N, Y, N, N, , 0, 0,

BO "730_C3", "C3-OVD", "Chiller-3 Override On"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO5", N
    UNITS "Off", "**On**", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_C3", "C3-USE", "Chiller-3 In Service Cmd"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DCO4", N
    UNITS "No!!!", "Yes", Y, Y, Y
    RESET N
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

CS "730_C3", "ALL-PNTS", "CS MODEL - Chiller-3 Cmd"
    MODEL "730_CH3"
~This Model not found in Model Database.
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "BD_18", "BD_18"
    FORMAT 1

BO "730_C3", "C3-C", "Chiller-3 Enable Cmd"
    HARDWARE "NC-43HW", "730_CH2"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DO4", Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER 5, 1, 0, 255
    FEEDBACK "730_C3", "C3-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_C3", "C3-STS", "Chiller-3 Status"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI1"
    INIT N, 2, 255, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

BI "730_C3", "C3-ALM", "Chiller-3 Safeties"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI2"
    INIT N, 1, 30, N
    UNITS "Normal", "Alm!!!"
    REPORT N, Y, N, N, , 0, 0,

BI "730_C3", "C3-XOK", "Chiller-3 Seq Failure"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS3"
    INIT N, 1, 30, N
    UNITS "No", "Yes!!!"
    REPORT N, Y, N, N, 3, 6, 2,

BI "730_C3", "C3-OFN", "Chiller-3 Off Normal"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS1"
    INIT N, 1, 30, N
    UNITS "No", "Yes!!!"
    REPORT N, Y, N, N, , 0, 0,

BI "730_C3", "C3-HIT", "Chiller-3 High Temp"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS2"
    INIT N, 1, 30, N
    UNITS "No", "Yes!!!"
    REPORT N, Y, N, N, , 0, 0,

BI "730_C3", "PMPS-XOK", "Chiller-3 Pumps Off Norm"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS4"
    INIT N, 1, 30, N
    UNITS "No", "Yes!!!"
    REPORT N, Y, N, N, , 0, 0,

BI "730_C3", "CHWP3-HX", "CHWP-3 Run for HEX"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS16"
    INIT N, 0, 30, N
    UNITS "No", "Yes"
    REPORT N, Y, N, N, , 0, 0,

BO "730_C3", "CHWP3-C", "Chil Wtr Pump-3 Cmd"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DO4", Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER 5, 1, 0, 255
    FEEDBACK "730_C3", "CHWP3-S", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_C3", "CHWP3-S", "Chil Wtr Pump-3 Status"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI3"
    INIT N, 2, 60, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

BD "730_C3", "CDW-PUMP", "Schedule Water Treatment"
    GRAPHICS 0, 0
    UNITS "Off", "!!On!!"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 0

BI "730_C3", "CDWP6-HX", "CDWP-6 Run for HEX"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "LRS18"
    INIT N, 0, 30, N
    UNITS "No", "Yes"
    REPORT N, Y, N, N, , 0, 0,

BO "730_C3", "CDWP6-C", "Cond Wtr Pump-6 Cmd"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DO5", Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER 5, 1, 0, 255
    FEEDBACK "730_C3", "CDWP6-S", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_C3", "CDWP6-S", "Cond Wtr Pump-6 Status"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "DI4"
    INIT N, 2, 60, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

AOS "730_C3", "CHWS-HL", "Chil Wtr Sup High Limit"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "ACO3", N
    INIT 59.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "730_C3", "CHWS3-T", "Chlr-3 Chil Wtr Sup Temp"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI1"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

AI "730_C3", "CHWR3-T", "Chlr-3 Chil Wtr Ret Temp"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI2"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

AI "730_C3", "CDWS3-T", "Chlr-3 Cond Wtr Sup Temp"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI3"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

AI "730_C3", "CDWR3-T", "Chlr-3 Cond Wtr Ret Temp"
    HARDWARE "NC-43HW", "730_CH3"
    GRAPHICS 0, 0
    DCDRHW "DX9100", "AI4"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

JCB "730_C3", "CDW_PUMP"

JCB "730_C3", "C3-RemSS"

AI "730_4FL", "EVOC-T", "EVOC Zone Temperature"
    HARDWARE "NC-43HW", "730_5-5"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 0, 3, 2, 0

AOS "730_4FL", "EVOC-CSP", "EVOC Cooling Setpoint"
    HARDWARE "NC-43HW", "730_5-5"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 245, N
    INIT 76.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AOS "730_4FL", "EVOC-DMP", "EVOC Zone Damper Command"
    HARDWARE "NC-43HW", "730_5-5"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

AOS "730_4FL", "EVOC-HSP", "EVOC Heating Setpoint"
    HARDWARE "NC-43HW", "730_5-5"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 252, N
    INIT 72.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

BO "730_4FL", "EVOC-DHT", "EVOC Duct Heater S/S"
    HARDWARE "NC-43HW", "730_5-5"
    GRAPHICS 0, 0
    N2OPENHW "BO", 1, Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER
    REPORT N, Y, N, N, , 0, 0, 0

BI "730_3FL", "STC-MODE", "Static Pressure Mode"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 0, 30, N
    UNITS "Dis", "Ena"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_3FL", "STC-STPT", "Static Pressure Setpoint"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 5.000000e-002, Y, Y
    UNITS "Inwc", 3
    REPORT N, Y, N, N, 0

AI "730_3FL", "STATIC", "Static Pressure"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "Inwc", 3
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 0

AOS "730_3FL", "RELD-CMD", "Relief Damper Command"
    HARDWARE "NC-43HW", "730_3-4"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

BO "730_2-3N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_2-3"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_2-3N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_2-3"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_2-3N", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "730_2-3N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_2-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_2-3N", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-43HW", "730_2-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_2-3N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_2-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 50.00000, 65.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 1

AOS "730_2-3N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_2-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "730_2-3N", "Zn-Sp", "Zone Stpt (VFD)"
    HARDWARE "NC-43HW", "730_2-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_2-3N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_2-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 78.00000, 10.00000, 65.00000, 86.00000, 1
    REPORT N, Y, N, N, 0, 0, 0, 2, 2, 0

AOS "730_2-3N", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-43HW", "730_2-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "730_2-3N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_2-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_2-3N", "WTR-DET", "Water Detection Status"
    HARDWARE "NC-43HW", "730_2-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 6, 6, 2, 5

BI "730_2-3N", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_2-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 15, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

CS "730_2-3N", "ALL-PNTS", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-43HW", "730_2-3"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

AI "730_2-3N", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V2-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 1
    UNITS "HZ", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_2-3N", "VFD-KW", "VFD-KW"
    HARDWARE "NC-43HW", "730_V2-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "KW", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_2-3N", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V2-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

CS "730_7-3N", "ALL-PNTS", "CS MODEL - Act Dis Stpt"
    MODEL "U_MASP5C"
    HARDWARE "NC-43HW", "730_7-3"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

BO "730_7-3N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_7-3"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_7-3N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_7-3"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_7-3N", "SAF-STS", Y
    REPORT N, Y, N, N, 3, 0, 2, 0

BI "730_7-3N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_7-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 60, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 0

AOS "730_7-3N", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-43HW", "730_7-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 129, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_7-3N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_7-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "730_7-3N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_7-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, Y, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 0

AOS "730_7-3N", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-43HW", "730_7-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 247, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_7-3N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_7-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 74.00000, 10.00000, 65.00000, 95.00000, 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AOS "730_7-3N", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-43HW", "730_7-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, Y, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "730_7-3N", "H2-ALM", "Hydrogen High Alm Status"
    HARDWARE "NC-43HW", "730_7-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 0, 120, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_7-3N", "EXF71-LH", "Exhaust Fan-71 Low/High"
    HARDWARE "NC-43HW", "730_7-3"
    GRAPHICS 0, 0
    N2OPENHW "BO", 4, Y
    UNITS "Low", "High", N, Y, N
    RESET N
    TIMER
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_7-3N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_7-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_7-3N", "WTR-DET", "Water Detection Status"
    HARDWARE "NC-43HW", "730_7-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 6, 6, 2, 5

BI "730_7-3N", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_7-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 6
    INIT N, 1, 10, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AI "730_7-3N", "VFD_FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V7-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 1
    UNITS "HZ", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_7-3N", "VFD-KW", "VFD-KW"
    HARDWARE "NC-43HW", "730_V7-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "KW", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_7-3N", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V7-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

JCB "730_7-3N", "OAF_CTL"

JCB "730_7-3N", "stpt"

BO "730_2-1N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_2-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_2-1N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_2-1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_2-1N", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "730_2-1N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_2-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_2-1N", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-43HW", "730_2-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_2-1N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_2-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "730_2-1N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_2-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "730_2-1N", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-43HW", "730_2-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_2-1N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_2-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 78.00000, 10.00000, , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AOS "730_2-1N", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-43HW", "730_2-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "730_2-1N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_2-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_2-1N", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_2-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 1, 0

AI "730_2-1N", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V2-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "%", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_2-1N", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V2-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AI "730_2-1N", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-43HW", "730_V2-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_2-1N", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-43HW", "730_V2-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "730_2-1N", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 0.0
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "730_2-1N", "vfd_spd"

JCB "730_2-1N", "stpt"

JCB "730_2-1N", "KW-VFD"

BO "730_6-5N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_6-5"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_6-5N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_6-5"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_6-5N", "SAF-STS", Y
    REPORT N, Y, N, N, 3, 0, 2, 0

BI "730_6-5N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_6-5"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_6-5N", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-43HW", "730_6-5"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_6-5N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_6-5"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 1.000000, , , 45.00000, 68.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "730_6-5N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_6-5"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, Y, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

AOS "730_6-5N", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-43HW", "730_6-5"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_6-5N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_6-5"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 78.00000, 10.00000, 65.00000, 85.00000, 1
    REPORT N, Y, N, N, 1, 1, 0, 2, 2, 0

AOS "730_6-5N", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-43HW", "730_6-5"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, Y, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "730_6-5N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_6-5"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_6-5N", "WTR-DET", "Water Detection Status"
    HARDWARE "NC-43HW", "730_6-5"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 6, 6, 2, 5

BI "730_6-5N", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_6-5"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 15, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

CS "730_6-5N", "ALL-PNTS", "CS MODEL - Act Dis Dtpt"
    MODEL "U_100%1C"
    HARDWARE "NC-43HW", "730_6-5"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

AI "730_6-5N", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V6-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "%", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_6-5N", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V6-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AI "730_6-5N", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-43HW", "730_V6-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_6-5N", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-43HW", "730_V6-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "730_6-5N", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "730_6-5N", "ZNT_DUP"

JCB "730_6-5N", "stpt"

JCB "730_6-5N", "KW-VFD"

BO "730_4-1N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_4-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_4-1N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_4-1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_4-1N", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "730_4-1N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_4-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_4-1N", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-43HW", "730_4-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_4-1N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_4-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AOS "730_4-1N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_4-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "730_4-1N", "Zn-Sp", "Zone Stpt (for VFD COMM)"
    HARDWARE "NC-43HW", "730_4-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_4-1N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_4-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 76.00000, 10.00000, 55.00000, 86.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "730_4-1N", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-43HW", "730_4-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

AI "730_4-1N", "Z-HUMD", "Zone Humidity"
    HARDWARE "NC-43HW", "730_4-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "% RH", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "730_4-1N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_4-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_4-1N", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_4-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 15, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

CS "730_4-1N", "ALL-PNTS", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-43HW", "730_4-1"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

AI "730_4-1N", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V4-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "HZ", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_4-1N", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V4-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AI "730_4-1N", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-43HW", "730_V4-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_4-1N", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-43HW", "730_V4-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "730_4-1N", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

BI "730_4-1N", "WTR-DET", "Floor Water Detector"
    HARDWARE "NC-43HW", "730_4-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 11, 0, 2, 5

JCB "730_4-1N", "vfd_spd"

JCB "730_4-1N", "stpt"

JCB "730_4-1N", "KW-VFD"

BO "730_4-2N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_4-2"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_4-2N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_4-2"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_4-2N", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 1, 0

BI "730_4-2N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_4-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_4-2N", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-43HW", "730_4-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_4-2N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_4-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "730_4-2N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_4-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "730_4-2N", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-43HW", "730_4-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_4-2N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_4-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 76.00000, 10.00000, , 85.00000, 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AOS "730_4-2N", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-43HW", "730_4-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "730_4-2N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_4-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_4-2N", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_4-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 15, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

CS "730_4-2N", "ALL-PNTS", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-43HW", "730_4-2"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

AI "730_4-2N", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V4-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "HZ", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_4-2N", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V4-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AI "730_4-2N", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-43HW", "730_V4-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_4-2N", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-43HW", "730_V4-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "730_4-2N", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

BI "730_4-2N", "WTR-DET", "Floor Water Detector"
    HARDWARE "NC-43HW", "730_4-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 11, 0, 2, 5

JCB "730_4-2N", "KW-VFD"

BO "730_5-1N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_5-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_5-1N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_5-1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_5-1N", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "730_5-1N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_5-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_5-1N", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-43HW", "730_5-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_5-1N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_5-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET , , , , 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "730_5-1N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_5-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "730_5-1N", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-43HW", "730_5-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_5-1N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_5-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 76.00000, 10.00000, 65.00000, 86.00000, 1
    REPORT N, Y, N, N, 0, 0, 0, 2, 2, 0

AOS "730_5-1N", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-43HW", "730_5-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "730_5-1N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_5-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_5-1N", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_5-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

CS "730_5-1N", "ALL-PNTS", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-43HW", "730_5-1"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

AI "730_5-1N", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V5-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "%", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_5-1N", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V5-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AI "730_5-1N", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-43HW", "730_V5-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_5-1N", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-43HW", "730_V5-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "730_5-1N", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

BI "730_5-1N", "WTR-DET", "Floor Water Detector"
    HARDWARE "NC-43HW", "730_5-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 11, 0, 2, 5

JCB "730_5-1N", "ZNT_DUP"

JCB "730_5-1N", "vfd_spd"

JCB "730_5-1N", "stpt"

JCB "730_5-1N", "KW-VFD"

BO "730_5-2N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_5-2"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_5-2N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_5-2"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_5-2N", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_5-2N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_5-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 1, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_5-2N", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-43HW", "730_5-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_5-2N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_5-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "730_5-2N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_5-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "730_5-2N", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-43HW", "730_5-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_5-2N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_5-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 76.00000, 10.00000, 55.00000, 86.00000, 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "730_5-2N", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-43HW", "730_5-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

AI "730_5-2N", "Z-HUMD", "Zone Humidity"
    HARDWARE "NC-43HW", "730_5-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "% RH", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "730_5-2N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_5-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_5-2N", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_5-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, , 0, 0, 0

CS "730_5-2N", "ALL-PNTS", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-43HW", "730_5-2"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

AI "730_5-2N", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V5-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "%", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_5-2N", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V5-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AI "730_5-2N", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-43HW", "730_V5-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_5-2N", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-43HW", "730_V5-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "730_5-2N", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

BI "730_5-2N", "WTR-DET", "Floor Water Detector"
    HARDWARE "NC-43HW", "730_5-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 11, 0, 2, 5

JCB "730_5-2N", "KW-VFD"

BO "730_3-1N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_3-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_3-1N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_3-1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_3-1N", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "730_3-1N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_3-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 0

AOS "730_3-1N", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-43HW", "730_3-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_3-1N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_3-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "730_3-1N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_3-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "730_3-1N", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-43HW", "730_3-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_3-1N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_3-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 74.00000, 10.00000, 55.00000, 86.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "730_3-1N", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-43HW", "730_3-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

AI "730_3-1N", "Z-HUMD", "Zone Humidity"
    HARDWARE "NC-43HW", "730_3-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "% RH", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "730_3-1N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_3-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_3-1N", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_3-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

CS "730_3-1N", "ALL-PNTS", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-43HW", "730_3-1"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

AI "730_3-1N", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V3-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "%", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_3-1N", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V3-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AI "730_3-1N", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-43HW", "730_V3-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_3-1N", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-43HW", "730_V3-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "730_3-1N", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

BI "730_3-1N", "WTR-DET", "Floor Water Detector"
    HARDWARE "NC-43HW", "730_3-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 11, 0, 2, 5

JCB "730_3-1N", "vfd_spd"

JCB "730_3-1N", "stpt"

JCB "730_3-1N", "KW-VFD"

BO "730_3-2N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_3-2"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_3-2N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_3-2"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_3-2N", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 5

BI "730_3-2N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_3-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_3-2N", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-43HW", "730_3-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_3-2N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_3-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "730_3-2N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_3-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "730_3-2N", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-43HW", "730_3-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_3-2N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_3-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 74.00000, 10.00000, 62.00000, 86.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "730_3-2N", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-43HW", "730_3-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "730_3-2N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_3-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_3-2N", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_3-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

CS "730_3-2N", "ALL-PNTS", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-43HW", "730_3-2"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

AI "730_3-2N", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V3-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "%", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_3-2N", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V3-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AI "730_3-2N", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-43HW", "730_V3-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_3-2N", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-43HW", "730_V3-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "730_3-2N", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, Y, N, , , 0, 0, 0, 0

BI "730_3-2N", "WTR-DET", "Floor Water Detector"
    HARDWARE "NC-43HW", "730_3-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 11, 0, 2, 0

JCB "730_3-2N", "KW-VFD"

BO "730_5-3N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_5-3"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_5-3N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_5-3"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_5-3N", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_5-3N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_5-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AI "730_5-3N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_5-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "730_5-3N", "Z-STPT", "Zone Setpoint"
    HARDWARE "NC-43HW", "730_5-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 129, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "730_5-3N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_5-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 0.1000000, , , 65.00000, 89.00000, 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "730_5-3N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_5-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_5-3N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_5-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

BI "730_5-3N", "WTR-DET", "Floor Water Detector"
    HARDWARE "NC-43HW", "730_5-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 11, 0, 2, 5

BO "730_5-4N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_5-4"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_5-4N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_5-4"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_5-4N", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "730_5-4N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_5-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_5-4N", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-43HW", "730_5-4"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_5-4N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_5-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "730_5-4N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_5-4"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "730_5-4N", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-43HW", "730_5-4"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_5-4N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_5-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 75.00000, 10.00000, 55.00000, 86.00000, 1
    REPORT N, Y, N, N, 0, 0, 0, 2, 2, 0

AOS "730_5-4N", "VFD-O", "VFD Cmd"
    HARDWARE "NC-43HW", "730_5-4"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "730_5-4N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_5-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_5-4N", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_5-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 15, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

CS "730_5-4N", "ALL-PNTS", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-43HW", "730_5-4"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

AI "730_5-4N", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V5-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "%", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_5-4N", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V5-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AI "730_5-4N", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-43HW", "730_V5-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_5-4N", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-43HW", "730_V5-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "730_5-4N", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

BI "730_5-4N", "WTR-DET", "Floor Water Detector"
    HARDWARE "NC-43HW", "730_5-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 11, 0, 2, 0

JCB "730_5-4N", "vfd_spd"

JCB "730_5-4N", "stpt"

JCB "730_5-4N", "KW-VFD"

BO "730_5-5N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_5-5"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_5-5N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_5-5"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_5-5N", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "730_5-5N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_5-5"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_5-5N", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-43HW", "730_5-5"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_5-5N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_5-5"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AOS "730_5-5N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_5-5"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "730_5-5N", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-43HW", "730_5-5"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_5-5N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_5-5"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 75.00000, 10.00000, 65.00000, 86.00000, 1
    REPORT N, Y, N, N, 0, 0, 0, 2, 2, 0

AOS "730_5-5N", "VFD-O", "VFD Cmd"
    HARDWARE "NC-43HW", "730_5-5"
    GRAPHICS 0, 0
    N2OPENHW "AO", 3, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "730_5-5N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_5-5"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_5-5N", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_5-5"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 15, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

CS "730_5-5N", "ALL-PNTS", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-43HW", "730_5-5"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

AI "730_5-5N", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V5-5"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "%", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_5-5N", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V5-5"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AI "730_5-5N", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-43HW", "730_V5-5"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_5-5N", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-43HW", "730_V5-5"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "730_5-5N", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

BI "730_5-5N", "WTR-DET", "Floor Water Detector"
    HARDWARE "NC-43HW", "730_5-5"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 11, 0, 2, 0

JCB "730_5-5N", "KW-VFD"

CS "730_6-4N", "ALL-PNTS", "CS MODEL - Occ Clg Stpt"
    MODEL "U1RTOP_C"
    HARDWARE "NC-43HW", "730_6-4"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 1

BO "730_6-4N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_6-4"
    GRAPHICS 0, 0
    N2OPENHW "BD", 229, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_6-4N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_6-4"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER
    FEEDBACK "730_6-4N", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 6, 2, 5

BI "730_6-4N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_6-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AI "730_6-4N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_6-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 0.1000000, , , 64.00000, 87.00000, 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AI "730_6-4N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_6-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "730_6-4N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_6-4"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

BI "730_6-4N", "WTR-DET", "Floor Water Detector"
    HARDWARE "NC-43HW", "730_6-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 11, 0, 2, 5

BO "730_2-2N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_2-2"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_2-2N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_2-2"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_2-2N", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "730_2-2N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_2-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_2-2N", "DA-SP", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-43HW", "730_2-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_2-2N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_2-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "730_2-2N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_2-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "730_2-2N", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-43HW", "730_2-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_2-2N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_2-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 78.00000, 10.00000, , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AOS "730_2-2N", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-43HW", "730_2-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

AI "730_2-2N", "Z-HUMD", "Zone Humidity"
    HARDWARE "NC-43HW", "730_2-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "% RH", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "730_2-2N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_2-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "730_2-2N", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_2-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AI "730_2-2N", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V2-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "%", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_2-2N", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V2-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AI "730_2-2N", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-43HW", "730_V2-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_2-2N", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-43HW", "730_V2-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "730_2-2N", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

BI "730_2-2N", "WTR-DET", "Floor Water Detector"
    HARDWARE "NC-43HW", "730_2-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 11, 0, 2, 0

JCB "730_2-2N", "KW-VFD"

AI "730_7-1N", "OA-TEMP", "Outside Air Temperature"
    HARDWARE "NC-43HW", "730_7-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 1
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 4

BO "730_7-1N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_7-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "730_7-1N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_7-1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_7-1N", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "730_7-1N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_7-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_7-1N", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-43HW", "730_7-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_7-1N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_7-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "730_7-1N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_7-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 0

AOS "730_7-1N", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-43HW", "730_7-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_7-1N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_7-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 74.00000, 10.00000, 65.00000, 85.00000, 1
    REPORT N, Y, N, N, 1, 1, 0, 5, 2, 0

AOS "730_7-1N", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-43HW", "730_7-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 3, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

AI "730_7-1N", "Z-HUMD", "Zone Humidity"
    HARDWARE "NC-43HW", "730_7-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "% RH", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AI "730_7-1N", "MA-TEMP", "Mixed Air Temperature"
    HARDWARE "NC-43HW", "730_7-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Deg F", 1
    ALARMSET , , , 50.00000, , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "730_7-1N", "RACO2-SP", "Return Air CO2 Setpoint"
    HARDWARE "NC-43HW", "730_7-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 153, N
    INIT 900.0000, Y, Y
    UNITS "PPM", 0
    REPORT N, Y, N, N, 5

AI "730_7-1N", "RA-CO2", "Return Air CO2 Reading"
    HARDWARE "NC-43HW", "730_7-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "PPM", 0
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "730_7-1N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_7-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_7-1N", "DMP-CMD", "Damper Command"
    HARDWARE "NC-43HW", "730_7-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

BI "730_7-1N", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_7-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AI "730_7-1N", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V7-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "%", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_7-1N", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V7-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AI "730_7-1N", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-43HW", "730_V7-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_7-1N", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-43HW", "730_V7-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "730_7-1N", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "730_7-1N", "vfd_spd"

JCB "730_7-1N", "stpt"

JCB "730_7-1N", "KW-VFD"

AI "730_7-2N", "OA-TEMP", "Outside Air Temperature"
    HARDWARE "NC-43HW", "730_7-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 1
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 4

BO "730_7-2N", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-43HW", "730_7-2"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "730_7-2N", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-43HW", "730_7-2"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "730_7-2N", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "730_7-2N", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-43HW", "730_7-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_7-2N", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-43HW", "730_7-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, N, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_7-2N", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-43HW", "730_7-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "730_7-2N", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-43HW", "730_7-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 0

AOS "730_7-2N", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-43HW", "730_7-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, N, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "730_7-2N", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-43HW", "730_7-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 74.00000, 10.00000, 60.00000, 86.00000, 1
    REPORT N, Y, N, N, 1, 1, 0, 5, 2, 0

AOS "730_7-2N", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-43HW", "730_7-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 3, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

AI "730_7-2N", "MA-TEMP", "Mixed Air Temperature"
    HARDWARE "NC-43HW", "730_7-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Deg F", 1
    ALARMSET , , , 50.00000, , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "730_7-2N", "RACO2-SP", "Return Air CO2 Setpoint"
    HARDWARE "NC-43HW", "730_7-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 153, N
    INIT 900.0000, Y, Y
    UNITS "PPM", 0
    REPORT N, Y, N, N, 5

AI "730_7-2N", "RA-CO2", "Return Air CO2 Reading"
    HARDWARE "NC-43HW", "730_7-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "PPM", 0
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "730_7-2N", "FILTER", "Filter Status"
    HARDWARE "NC-43HW", "730_7-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "730_7-2N", "DMP-CMD", "Damper Command"
    HARDWARE "NC-43HW", "730_7-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

BI "730_7-2N", "VFD-A", "VFD Alarm"
    HARDWARE "NC-43HW", "730_7-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AI "730_7-2N", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-43HW", "730_V7-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "%", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "730_7-2N", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-43HW", "730_V7-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AI "730_7-2N", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-43HW", "730_V7-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "730_7-2N", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-43HW", "730_V7-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "730_7-2N", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

BI "730_7-2N", "WTR-DET", "Floor Water Detector"
    HARDWARE "NC-43HW", "730_7-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, , 0, 0, 0

JCB "730_7-2N", "KW-VFD"

******************************************************************************
*
*                      SUMMARY FOR BELLATL NC-43
*
*                            HARDWARE OBJECTS
*
*        D600s   0          DCDRs   6           DCMs   0        DCM140s   0   
*         DSCs   0       DSC8500s   0          FIREs   0           FPUs   0   
*         LCDs   0           LONs   0        N2OPENs  46            XMs   0   
*
*  Total Hardware Objects = 52
*
*
*                            SOFTWARE OBJECTS
*
*        ACMs   0            ADs  59            AIs 169           AODs   0   
*        AOSs 137            BDs  64            BIs 157            BOs 102   
*      C210As   0         C260As   0         C260Xs   0         C500Xs   0   
*         CSs  43**        DLLRs   0           JCBs  69           LCGs   0   
*         MCs   0           MSDs   0           MSIs   0           MSOs   0   
*       PIDLs   0        READERs   0          ZONEs   0   
*
*  Total Software Objects = 800
*
*  Total Objects = 852 ** object counts followed by ** signify
*                        object types which had errors
*
*
*                                FEATURES 
*
*       CARDs   0      TIMEZONEs   0   
*
*  Total Features = 0
*
******************************************************************************
* 18 errors decompiling - Decompiled source has errors that will not compile
******************************************************************************
