
******************************************************************************
* Johnson Controls Inc. Metasys (TM) DDL Decompiler Release 12.00
* Copyright (C) 2001 Johnson Controls, Inc.   All Rights Reserved.
* Portions Copyright (C) 1987-1988 Lattice Inc.   All Rights Reserved.
*
* Mon May 07 07:00:54 2018
*
* archive decompiled from:
*      C:\Project\Bellatl\win.ini FMSDATA=C:\Project\Bellatl
*
******************************************************************************
@NC "BELLATL", "NC-16"


N2OPEN "NC-16HW", "1200_SB1", "N2 Type UNT Addr-31"
    ADDRESS 31, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4,  6
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    2
*  BO slots used =    3
*  IF slots used =  129
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_SB2", "N2 Type UNT Addr-30"
    ADDRESS 30, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    1,  2,  3,  4
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1
*  BO slots used =    3
*  IF slots used =  129
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_B-1", "N2 Type UNT Addr-32"
    ADDRESS 32, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4,  6
*  BI slots used =    1,  2
*  AO slots used =    2
*  BO slots used =    3
*  IF slots used =  129
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_1-1", "N2 Type UNT Addr-33"
    ADDRESS 33, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_1-2", "N2 Type UNT Addr-34"
    ADDRESS 34, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2,  3,  4,  6
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_1-3", "N2 Type UNT Addr-35"
    ADDRESS 35, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2
*  AO slots used =    2
*  BO slots used =    3
*  IF slots used =  129
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_2-1", "N2 Type UNT Addr-36"
    ADDRESS 36, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4,  5
*  BI slots used =    1,  2,  3
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_2-2", "N2 Type UNT Addr-37"
    ADDRESS 37, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2,  3
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_3-1", "N2 Type UNT111-1 Addr-40"
    ADDRESS 40, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4,  5
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_3-2", "N2 Type UNT111-1 Addr-41"
    ADDRESS 41, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4,  5
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_3-3", "N2 Type UNT111-1 Addr-61"
    ADDRESS 61, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4,  5,  6
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2,  3,  4
*  BO slots used =    3
*  IF slots used =  142,236,242,243
*  II slots used =  
* IBy slots used =  197,244
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_4-1", "N2 Type UNT Addr-42"
    ADDRESS 42, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    1,  2,  3,  4,  6
*  BI slots used =    1,  2,  3,  4,  6
*  AO slots used =    1,  2,  3
*  BO slots used =    3
*  IF slots used =  142,153,248
*  II slots used =  
* IBy slots used =  197,244
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_4-2", "N2 Type UNT Addr-43"
    ADDRESS 43, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    1,  2,  3,  4,  5
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2,  4
*  BO slots used =    3
*  IF slots used =  142,153,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_4-3", "N2 Type UNT Addr-44"
    ADDRESS 44, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2,  3
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_4-4", "N2 Type UNT Addr-45"
    ADDRESS 45, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_5-1", "N2 Type UNT Addr-46"
    ADDRESS 46, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4,  5
*  BI slots used =    1,  2,  3
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_5-2", "N2 Type UNT Addr-47"
    ADDRESS 47, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2,  3
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_6-1", "N2 Type UNT Addr-48"
    ADDRESS 48, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    2,  3,  4,  5
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_6-2", "N2 Type UNT Addr-49"
    ADDRESS 49, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    2,  3,  4,  5
*  BI slots used =    1,  2,  3
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_6-3", "N2 Type UNT111-1 Addr-59"
    ADDRESS 59, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    2,  3,  4,  5
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_6-4", "N2 Type UNT111-1 Addr-60"
    ADDRESS 60, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    2,  3,  4,  5
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_7-1", "N2 Type UNT Addr-50"
    ADDRESS 50, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4,  5
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_7-2", "N2 Type UNT Addr-51"
    ADDRESS 51, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  4
*  BI slots used =    1,  2,  3
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_8-1", "N2 Type UNT Addr-52"
    ADDRESS 52, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  5
*  BI slots used =    1,  2,  3,  4
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_8-2", "N2 Type UNT Addr-53"
    ADDRESS 53, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    3,  5
*  BI slots used =    1,  2,  3
*  AO slots used =    1,  2
*  BO slots used =    3
*  IF slots used =  142,248
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_8-3", "N2 Type UNT1144 Addr-106"
    ADDRESS 106, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    1,  2,  3
*  BI slots used =    1,  2,  3,  4,  6,  7
*  AO slots used =    1,  2
*  BO slots used =    2
*  IF slots used =  240,241
*  II slots used =  
* IBy slots used =  244
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_8-4", "N2 Type UNT1144 Addr-107"
    ADDRESS 107, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =  
*  BI slots used =    1,  2,  3,  4,  6,  7
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  242,243,244
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_8-8", "1200 8flr CRACs ADD-29"
    ADDRESS 29, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    1,  2,  3
*  BI slots used =    1,  2,  3,  4,  5
*  AO slots used =  
*  BO slots used =    1,  2
*  IF slots used =   21, 22,129
*  II slots used =   40, 42, 44, 45, 46
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_PH1", "N2 Type UNT Addr-55"
    ADDRESS 55, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =  
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  244
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_D56", "N2 Type UNT Addr-56"
    ADDRESS 56, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    1,  2,  3,  4,  5
*  BI slots used =    1,  2,  4
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_D57", "N2 Type UNT Addr-57"
    ADDRESS 57, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    1,  2,  3,  4,  5,  6
*  BI slots used =    1
*  AO slots used =  
*  BO slots used =    1
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_D58", "N2 Type UNT Addr-58"
    ADDRESS 58, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    1,  2
*  BI slots used =  
*  AO slots used =    1,  2
*  BO slots used =    1
*  IF slots used =  239,240,252
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

DCDR "NC-16HW", "1200_D62", "N2 Type XTM105 Addr=62"
    ADDRESS 62, 1, 3, "XTM"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
* Hardware References used = 2DI5
*                            2DI3
*                            2DI4
*                            1DI1
*                            1DI3
*                            1DI2
*                            2DI1
*                            1DI4
*                            2DI8
*                            2DI6
*                            2DI7
*                            1DI5
*                            1DI7
*                            1DI6
*                            2DI2
*                            1DI8
*                            AI1
*                            AI2
*                            
*

DCDR "NC-16HW", "1200_D63", "N2 Type XTM105 Addr=63"
    ADDRESS 63, 1, 3, "XTM"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
* Hardware References used = 1DI3
*                            1DI1
*                            1DI2
*                            1DI4
*                            1DI6
*                            1DI5
*                            1DI8
*                            1DI7
*                            2DI1
*                            2DI2
*                            2DI3
*                            2DI4
*                            2DI5
*                            2DI6
*                            2DI7
*                            2DI8
*                            AI2
*                            AI3
*                            AI1
*                            AI5
*                            AI6
*                            
*

N2OPEN "NC-16HW", "1200_D67", "N2 Type UNT110-1 Addr-67"
    ADDRESS 67, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =  
*  BI slots used =    1,  2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_9-1", "N2 Type UNT111-1 Addr-64"
    ADDRESS 64, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    1,  2,  3,  4
*  BI slots used =    1,  4
*  AO slots used =    1,  2
*  BO slots used =    1
*  IF slots used =  153
*  II slots used =  
* IBy slots used =  197,242,243,244
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_9-2", "N2 Type UNT111-1 Addr-65"
    ADDRESS 65, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    1,  3
*  BI slots used =    1,  4
*  AO slots used =    1,  2
*  BO slots used =    1,  2
*  IF slots used =  
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200_9-4", "N2 Type UNT111-1 Addr-66"
    ADDRESS 66, 1, 3, "UNT"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 1
*
*  AI slots used =    4
*  BI slots used =    1,  2
*  AO slots used =    2
*  BO slots used =    1,  3,  4
*  IF slots used =  
*  II slots used =  
* IBy slots used =  197
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V1-1", "1200 1-1 VFD ADD-26"
    ADDRESS 26, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V1-2", "1200 1-2 VFD ADD-27"
    ADDRESS 27, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V2-1", "1200 2-1 VFD ADD-69"
    ADDRESS 69, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V2-2", "1200 2-2 VFD ADD-70"
    ADDRESS 70, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V31B", "1200 3-1B VFD ADD-78"
    ADDRESS 78, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V32B", "1200 3-2B VFD ADD-79"
    ADDRESS 79, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V33B", "1200 3-3B VFD ADD-80"
    ADDRESS 80, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V4-1", "1200 4-2 VFD ADD-81"
    ADDRESS 81, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V4-2", "1200 4-1 VFD ADD-82"
    ADDRESS 82, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V4-3", "1200 4-3 VFD ADD-83"
    ADDRESS 83, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V4-4", "1200 4-4 VFD ADD-84"
    ADDRESS 84, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2,  5
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V5-1", "1200 5-2 VFD ADD-87"
    ADDRESS 87, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V5-2", "1200 5-1 VFD ADD-88"
    ADDRESS 88, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V6-1", "1200 6-1 VFD ADD-97"
    ADDRESS 97, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V6-2", "1200 6-2 VFD ADD-98"
    ADDRESS 98, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V7-1", "1200 7-1 VFD ADD-102"
    ADDRESS 102, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V7-2", "1200 7-2 VFD ADD-103"
    ADDRESS 103, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V8-1", "1200 8-1 VFD ADD-104"
    ADDRESS 104, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

N2OPEN "NC-16HW", "1200V8-2", "1200 8-2 VFD ADD-105"
    ADDRESS 105, 1, 3, "VND"
    GRAPHICS 0, 0
    REPORT N, N
*
* number of CS objects on this device: 0
*
*  AI slots used =    2,  6,  8
*  BI slots used =    2
*  AO slots used =  
*  BO slots used =  
*  IF slots used =  
*  II slots used =  
* IBy slots used =  
* IBt slots used =  
*

BO "1200_4-4", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_4-4"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200_4-4", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_4-4"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200_4-4", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "1200_4-4", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_4-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200_4-4", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_4-4"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_4-4", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_4-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "1200_4-4", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_4-4"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "1200_4-4", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_4-4"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_4-4", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_4-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 76.00000, 10.00000, 65.00000, 90.00000, 1
    REPORT N, Y, N, N, 0, 0, 0, 5, 2, 0

AOS "1200_4-4", "VFD-O", "VFD Cmd 0=26Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_4-4"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "1200_4-4", "VFD-STS", "VFD Status"
    HARDWARE "NC-16HW", "1200V4-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200_4-4", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200V4-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 5
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AI "1200_4-4", "VFD-FB", "VFD Feedback Freq"
    HARDWARE "NC-16HW", "1200V4-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Hertz", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_4-4", "VFD-AMPS", "VFD Motor Current"
    HARDWARE "NC-16HW", "1200V4-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "Amps", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_4-4", "VFD-VLTS", "VFD Motor Volts"
    HARDWARE "NC-16HW", "1200V4-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "Vac", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "1200_4-4", "VFD-KW", "VFD KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "1200_4-4", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_4-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty!"
    REPORT N, Y, N, N, , 0, 0, 5

JCB "1200_4-4", "KW-VFD"

CS "1200N8-1", "ALL-PNTS", "CS MODEL - Act Disc Stpt"
    MODEL "Ub100%1C"
~This Model not found in Model Database.
    HARDWARE "NC-16HW", "1200_8-1"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

BO "1200N8-1", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_8-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200N8-1", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_8-1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200N8-1", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200N8-1", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_8-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200N8-1", "LEAD", "Lead Unit"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, Y, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200N8-1", "LAG", "Lag Unit for 8-2"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200N8-1", "USE-LAG", "Cycle On Lag Unit"
    GRAPHICS 0, 0
    UNITS "No", "Yes!"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200N8-1", "OFF-NORM", "Unit Off Normal"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 11, 6, 2, 5

BD "1200N8-1", "HI-TEMP", "Unit Return High Temp"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 12, 6, 2, 5

AD "1200N8-1", "LEAD-HL", "Lead Fail Hi Ret Limit"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 80.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 2, 3, 4

AD "1200N8-1", "LAG-HL", "Lag Cycle Hi Ret Limit"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 78.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "1200N8-1", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_8-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200N8-1", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_8-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, 14, 14, 6, 3, 2, 5

AOS "1200N8-1", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_8-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "1200N8-1", "RA-Sp", "Ret Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_8-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 75.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200N8-1", "RA-TEMP", "Return Air Temperature"
    HARDWARE "NC-16HW", "1200_8-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "Deg F", 1
    ALARMSET 1.000000, , , 55.00000, 85.00000, 1
    REPORT N, Y, N, N, 15, 15, 6, 3, 2, 5

AOS "1200N8-1", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_8-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "1200N8-1", "VFD-STS", "VFD Status"
    HARDWARE "NC-16HW", "1200V8-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200N8-1", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_8-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AI "1200N8-1", "VFD-FB", "VFD Feedback Freq"
    HARDWARE "NC-16HW", "1200V8-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Hertz", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200N8-1", "VFD-AMPS", "VFD Motor Current"
    HARDWARE "NC-16HW", "1200V8-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "Amps", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200N8-1", "VFD-VLTS", "VFD Motor Volts"
    HARDWARE "NC-16HW", "1200V8-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "Vac", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "1200N8-1", "VFD-KW", "VFD KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "1200N8-1", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_8-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

JCB "1200N8-1", "KW-VFD"

JCB "1200N8-1", "OFF_NORM"

JCB "1200N8-1", "HI_TEMP"

JCB "1200N8-1", "vfd_spd"

JCB "1200N8-1", "stpt"

JCB "1200N8-1", "SAF_SS"

JCB "1200N8-1", "Lag_Ctl"

CS "1200N8-2", "ALL-PNTS", "CS MODEL - Act Disc Stpt"
    MODEL "Ub100%1C"
~This Model not found in Model Database.
    HARDWARE "NC-16HW", "1200_8-2"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

BO "1200N8-2", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_8-2"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200N8-2", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_8-2"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200N8-2", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200N8-2", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_8-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200N8-2", "LEAD", "Lead Unit"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, Y, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200N8-2", "LAG", "Lag Unit for 8-1"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200N8-2", "USE-LAG", "Cycle On Lag Unit"
    GRAPHICS 0, 0
    UNITS "No", "Yes!"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200N8-2", "OFF-NORM", "Unit Off Normal"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 11, 6, 2, 5

BD "1200N8-2", "HI-TEMP", "Unit Return High Temp"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 12, 6, 2, 5

AD "1200N8-2", "LEAD-HL", "Lead Fail Hi Ret Limit"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 80.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 2, 3, 4

AD "1200N8-2", "LAG-HL", "Lag Cycle Hi Ret Limit"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 78.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "1200N8-2", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_8-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200N8-2", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_8-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, 14, 14, 6, 3, 2, 5

AOS "1200N8-2", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_8-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "1200N8-2", "RA-Sp", "Ret Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_8-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 75.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200N8-2", "RA-TEMP", "Return Air Temperature"
    HARDWARE "NC-16HW", "1200_8-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "Deg F", 1
    ALARMSET 1.000000, , , 55.00000, 85.00000, 1
    REPORT N, Y, N, N, 15, 15, 6, 3, 2, 5

AOS "1200N8-2", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_8-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "1200N8-2", "VFD-STS", "VFD Status"
    HARDWARE "NC-16HW", "1200V8-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200N8-2", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_8-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AI "1200N8-2", "VFD-FB", "VFD Feedback Freq"
    HARDWARE "NC-16HW", "1200V8-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Hertz", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200N8-2", "VFD-AMPS", "VFD Motor Current"
    HARDWARE "NC-16HW", "1200V8-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "Amps", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200N8-2", "VFD-VLTS", "VFD Motor Volts"
    HARDWARE "NC-16HW", "1200V8-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "Vac", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "1200N8-2", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

BI "1200N8-2", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_8-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

JCB "1200N8-2", "KW-VFD"

JCB "1200N8-2", "OFF_NORM"

JCB "1200N8-2", "HI_TEMP"

JCB "1200N8-2", "SAF_SS"

JCB "1200N8-2", "Lag_Ctl"

CS "1200_6-4", "ALL-PNTS", "CS MODEL - Act Disc Stpt"
    MODEL "Ub100%1C"
~This Model not found in Model Database.
    HARDWARE "NC-16HW", "1200_6-4"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

BO "1200_6-4", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_6-4"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200_6-4", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_6-4"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER
    FEEDBACK "1200_6-4", "SAF-STS", Y
    REPORT N, Y, N, N, 3, 6, 2, 5

BI "1200_6-4", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_6-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200_6-4", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_6-4"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_6-4", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_6-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 38.00000, 85.00000, 1
    REPORT N, Y, N, N, 14, 14, 6, 3, 2, 5

AOS "1200_6-4", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_6-4"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

AI "1200_6-4", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_6-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, , , 60.00000, 85.00000, 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

AI "1200_6-4", "Z-TEMP_H", "Zone Temperature Highest"
    HARDWARE "NC-16HW", "1200_6-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

AOS "1200_6-4", "RA-Sp", "Ret Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_6-4"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 75.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "1200_6-4", "RA-TEMP", "Return Air Temperature"
    HARDWARE "NC-16HW", "1200_6-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Deg F", 1
    ALARMSET 0.5000000, , , 60.00000, 85.00000, 1
    REPORT N, Y, N, N, 15, 15, 6, 3, 2, 5

AOS "1200_6-4", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_6-4"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "% ", 1
    REPORT N, Y, N, N, 0

BI "1200_6-4", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_6-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "1200_6-4", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_6-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_6-4", "WTR-DET", "Water Detection Status"
    HARDWARE "NC-16HW", "1200_6-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 6, 6, 2, 5

CS "1200_6-3", "ALL-PNTS", "CS MODEL - Act Disc Stpt"
    MODEL "Ub100%1C"
~This Model not found in Model Database.
    HARDWARE "NC-16HW", "1200_6-3"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

BO "1200_6-3", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_6-3"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200_6-3", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_6-3"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER
    FEEDBACK "1200_6-3", "SAF-STS", Y
    REPORT N, Y, N, N, 3, 6, 2, 5

BI "1200_6-3", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_6-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200_6-3", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_6-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_6-3", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_6-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, 14, 14, 6, 3, 2, 5

AOS "1200_6-3", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_6-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

AI "1200_6-3", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_6-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, , , 60.00000, 85.00000, 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

AI "1200_6-3", "Z-TEMP_H", "Zone Temperature Highest"
    HARDWARE "NC-16HW", "1200_6-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

AOS "1200_6-3", "RA-Sp", "Ret Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_6-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 75.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "1200_6-3", "RA-Temp", "Return Air Temperature"
    HARDWARE "NC-16HW", "1200_6-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Deg F", 1
    ALARMSET 0.5000000, , , 60.00000, 85.00000, 1
    REPORT N, Y, N, N, 15, 15, 6, 3, 2, 5

AOS "1200_6-3", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_6-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "% ", 1
    REPORT N, Y, N, N, 0

BI "1200_6-3", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_6-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "1200_6-3", "WTR-DET", "Water Detection Status"
    HARDWARE "NC-16HW", "1200_6-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 6, 6, 2, 5

BI "1200_6-3", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_6-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

JCB "1200_6-3", "vfd_spd"

JCB "1200_6-3", "stpt"

CS "1200N6-2", "ALL-PNTS", "CS MODEL - Act Disc Stpt"
    MODEL "Ub100%1C"
~This Model not found in Model Database.
    HARDWARE "NC-16HW", "1200_6-2"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

BO "1200N6-2", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_6-2"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200N6-2", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_6-2"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200N6-2", "SAF-STS", Y
    REPORT N, Y, N, N, 3, 6, 2, 5

BI "1200N6-2", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_6-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 1, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200N6-2", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_6-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 60.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200N6-2", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_6-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, 14, 14, 6, 3, 2, 5

AOS "1200N6-2", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_6-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AI "1200N6-2", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_6-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, , , 60.00000, 85.00000, 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

AI "1200N6-2", "Z-TEMP_H", "Zone Temperature Highest"
    HARDWARE "NC-16HW", "1200_6-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

AOS "1200N6-2", "RA-Sp", "Ret Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_6-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 75.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "1200N6-2", "RA-TEMP", "Return Air Temperature"
    HARDWARE "NC-16HW", "1200_6-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Deg F", 1
    ALARMSET 0.5000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, 15, 15, 6, 3, 2, 5

AOS "1200N6-2", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_6-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "1200N6-2", "VFD-STS", "VFD Status"
    HARDWARE "NC-16HW", "1200V6-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200N6-2", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_6-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 6, 2, 5

AI "1200N6-2", "VFD-FB", "VFD Feedback Hertz"
    HARDWARE "NC-16HW", "1200V6-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Hertz", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200N6-2", "VFD-AMPS", "VFD Moter Current"
    HARDWARE "NC-16HW", "1200V6-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "Amps", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200N6-2", "VFD-VLTS", "VFD Motor Volts"
    HARDWARE "NC-16HW", "1200V6-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "Vac", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "1200N6-2", "VFD-KW", "VFD KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 0.0
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "1200N6-2", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_6-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

JCB "1200N6-2", "KW-VFD"

CS "1200N6-1", "ALL-PNTS", "CS MODEL - Act Disc Stpt"
    MODEL "Ub100%1C"
~This Model not found in Model Database.
    HARDWARE "NC-16HW", "1200_6-1"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

BO "1200N6-1", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_6-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200N6-1", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_6-1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200N6-1", "SAF-STS", Y
    REPORT N, Y, N, N, 3, 6, 2, 5

BI "1200N6-1", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_6-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200N6-1", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_6-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200N6-1", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_6-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, 14, 14, 6, 3, 2, 5

AOS "1200N6-1", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_6-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AI "1200N6-1", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_6-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, , , 60.00000, 85.00000, 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

AI "1200N6-1", "Z-TEMP_H", "Zone Temperature Highest"
    HARDWARE "NC-16HW", "1200_6-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

AOS "1200N6-1", "RA-Sp", "Ret Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_6-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 75.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "1200N6-1", "RA-Temp", "Return Air Temperature"
    HARDWARE "NC-16HW", "1200_6-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Deg F", 1
    ALARMSET 0.5000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, 15, 15, 6, 3, 2, 5

AOS "1200N6-1", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_6-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "1200N6-1", "VFD-STS", "VFD Status"
    HARDWARE "NC-16HW", "1200V6-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200N6-1", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_6-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AI "1200N6-1", "VFD-FB", "VFD Feedback Freq"
    HARDWARE "NC-16HW", "1200V6-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Hertz", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200N6-1", "VFD-AMPS", "VFD Motor Current"
    HARDWARE "NC-16HW", "1200V6-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "Amps", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200N6-1", "VFD-VLTS", "VFD Motor Volts"
    HARDWARE "NC-16HW", "1200V6-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "Vac", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "1200N6-1", "VFD-KW", "VFD KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 0.0
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "1200N6-1", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_6-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200N6-1", "WTR-DET", "Floor Water Detector"
    HARDWARE "NC-16HW", "1200_6-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 6, 6, 2, 5

JCB "1200N6-1", "ZNT_DUP"

JCB "1200N6-1", "KW-VFD"

JCB "1200N6-1", "vfd_spd"

JCB "1200N6-1", "stpt"

CS "1200_MOD", "1200_SB1", "CS MODEL - Zone Setpoint"
    MODEL "U_100%1C"
    HARDWARE "NC-16HW", "1200_SB1"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 1

CS "1200_MOD", "1200_SB2", "CS MODEL - Zone Setpoint"
    MODEL "U_100%1C"
    HARDWARE "NC-16HW", "1200_SB2"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 1

CS "1200_MOD", "1200_B-1", "CS MODEL - Zone Setpoint"
    MODEL "U_100%1C"
    HARDWARE "NC-16HW", "1200_B-1"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 1

CS "1200_MOD", "1200_1-1", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-16HW", "1200_1-1"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

CS "1200_MOD", "1200_1-2", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-16HW", "1200_1-2"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

CS "1200_MOD", "1200_1-3", "CS MODEL - Zone Setpoint"
    MODEL "U_100%1C"
    HARDWARE "NC-16HW", "1200_1-3"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 1

CS "1200_MOD", "1200_2-1", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-16HW", "1200_2-1"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

CS "1200_MOD", "1200_2-2", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-16HW", "1200_2-2"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

CS "1200_MOD", "1200_4-1", "CS MODEL - Act Dis Stpt"
    MODEL "U_MASP5C"
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

CS "1200_MOD", "1200_4-2", "CS MODEL - Act Dis Stpt"
    MODEL "U_MASP5C"
    HARDWARE "NC-16HW", "1200_4-2"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

CS "1200_MOD", "1200_4-3", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-16HW", "1200_4-3"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

CS "1200_MOD", "1200_4-4", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-16HW", "1200_4-4"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

CS "1200_MOD", "1200_5-1", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-16HW", "1200_5-1"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

CS "1200_MOD", "1200_5-2", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-16HW", "1200_5-2"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

CS "1200_MOD", "1200_7-1", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-16HW", "1200_7-1"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

CS "1200_MOD", "1200_7-2", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-16HW", "1200_7-2"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

CS "1200_MOD", "1200_PH1", "CS MODEL - Ret Air Stpt"
    MODEL "U_MASP6C"
    HARDWARE "NC-16HW", "1200_PH1"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 1

CS "1200_MOD", "1200_8-3", "CS MODEL - All Points"
    MODEL "UNT_PNTS"
    HARDWARE "NC-16HW", "1200_8-3"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "AI_2", "AI_2"
    FORMAT 1

BD "1200_8-7", "FMS-Rst", "CRAC-7&8 Reset of Alarms"
    GRAPHICS 0, 0
    UNITS "Off", "Reset"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 0

AOS "1200_8-7", "Lag-Stpt", "CRAC-7&8 Lag Unit Stpt"
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 129, N
    INIT 85.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

BO "1200_8-7", "CRAC7-C", "CRAC-7 Enable"
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    N2OPENHW "BO", 1, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200_8-7", "CRAC7-S", "CRAC-7 Status"
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 0, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_8-7", "CRAC7-A", "CRAC-7 Alarm Status"
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 1, 30, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 6, 2, 5

BD "1200_8-7", "CRAC7OfN", "CRAC-7 Off Normal Alarm"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 11, 6, 2, 5

BD "1200_8-7", "CRAC7-HT", "CRAC-7 High Temperature"
    ASSOCINP "CS", "NC-16HW", "CRAC-Pts", "BD_3"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 12, 6, 2, 5

~ERROR - 1200_8-7\CRAC7HiT is listed in the object entry database file as a BD
         object. This object cannot be found in the database file containing
          all data for all objects of type BD.
         (The object entry data base file contains a list of all of an
         NC's system\object names and their object type.)


AI "1200_8-7", "Z1-Temp", "Zone-1 Temperature"
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    N2OPENHW "AI", 1
    UNITS "Deg F", 1
    ALARMSET 1.000000, , , 65.00000, 85.00000, 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

AI "1200_8-7", "Z2-Temp", "Zone-2 Temperature"
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Deg F", 1
    ALARMSET 1.000000, , , 65.00000, 85.00000, 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

AI "1200_8-7", "Z3-Temp", "Zone-3 Temperature"
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 1.000000, , , 65.00000, 85.00000, 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

BI "1200_8-7", "Wtr-Det", "Under Flr Wtr Detect 7&8"
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    N2OPENHW "BI", 5
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 6, 6, 2, 5

BD "1200_8-7", "--------", "Rotate Info - Don't Adj"
    GRAPHICS 0, 0
    UNITS "------", "-----"
    INIT N, N, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

BD "1200_8-7", "Rotate-C", "CRAC-7&8 Rotate Command"
    GRAPHICS 0, 0
    UNITS "Off", "Rotate"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 0

BD "1200_8-7", "Rotate-S", "CRAC-7&8 Rotate Status"
    ASSOCINP "CS", "NC-16HW", "CRAC-Pts", "BD_2"
    GRAPHICS 0, 0
    UNITS "Off", "Rotate"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 0

AOS "1200_8-7", "Rot-Sts", "Rotation Status"
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    N2OPENHW "ADI", 46, Y
    INIT 0.0, Y, N
    UNITS "Number", 0
    REPORT N, Y, N, N, 0

AOS "1200_8-7", "CRAC7Out", "CRAC-7 Output"
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    N2OPENHW "ADI", 44, Y
    INIT 0.0, Y, N
    UNITS "Number", 0
    REPORT N, Y, N, N, 0

AOS "1200_8-7", "CRAC8Out", "CRAC-8 Output"
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    N2OPENHW "ADI", 45, Y
    INIT 0.0, Y, N
    UNITS "Number", 0
    REPORT N, Y, N, N, 0

AOS "1200_8-7", "CRAC7-AF", "CRAC-7 Air Flow Failure"
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    N2OPENHW "ADI", 40, Y
    INIT 0.0, Y, N
    UNITS "Number", 0
    REPORT N, Y, N, N, 0

~ERROR - 1200_8-7\CRAC8-AF is listed in the object entry database file as a AOS
         object. This object cannot be found in the database file containing
          all data for all objects of type AOS.
         (The object entry data base file contains a list of all of an
         NC's system\object names and their object type.)


BD "1200_8-7", "FMSRst-S", "FMS Reset Status"
    ASSOCINP "CS", "NC-16HW", "CRAC-Pts", "BD_1"
    GRAPHICS 0, 0
    UNITS "Off", "Reset"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 0

JCB "1200_8-7", "CRAC_Pts"

AOS "1200_8-7", "CRAC7-RT", "CRAC-7 Run Time Value"
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 21, N
    INIT 0.0, N, N
    UNITS "Hours", 1
    REPORT N, Y, N, N, 0

AOS "1200_8-7", "CRAC8-RT", "CRAC-8 Run Time Value"
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 22, N
    INIT 0.0, N, N
    UNITS "Hours", 1
    REPORT N, Y, N, N, 0

AOS "1200_8FL", "D8-2_Stp", "MD-8-2 Damper Setpoint"
    HARDWARE "NC-16HW", "1200_8-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 241, N
    INIT 78.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "1200_8FL", "D8-2_ZnT", "MD-8-2 Zone Temperature"
    HARDWARE "NC-16HW", "1200_8-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 1
    UNITS "Deg F", 1
    ALARMSET , , , , 85.00000, 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

AOS "1200_8FL", "D8-2_Dmp", "MD-8-2 Damper Command"
    HARDWARE "NC-16HW", "1200_8-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, Y, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

AOS "1200_8FL", "D8-3_Stp", "MD-8-3 Damper Setpoint"
    HARDWARE "NC-16HW", "1200_8-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 240, N
    INIT 78.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "1200_8FL", "D8-3_ZnT", "MD-8-3 Zone Temperature"
    HARDWARE "NC-16HW", "1200_8-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Deg F", 1
    ALARMSET , , , , 85.00000, 1
    REPORT N, Y, N, N, 1, 1, 6, 3, 2, 5

AOS "1200_8FL", "D8-3_Dmp", "MD-8-3 Damper Command"
    HARDWARE "NC-16HW", "1200_8-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, Y, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

BI "1200_8FL", "Pan-WDet", "Pan Water Detector Sts"
    HARDWARE "NC-16HW", "1200_8-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 6, 6, 2, 5

BI "1200_8FL", "H2-ALM", "Battery Hydrogen Hi Alm"
    HARDWARE "NC-16HW", "1200_8-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 6
    INIT N, 1, 120, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 45, 6, 1, 5

BO "1200_8FL", "EF8-1_SS", "Exhaust Fan 8-1 S/S"
    HARDWARE "NC-16HW", "1200_8-3"
    GRAPHICS 0, 0
    N2OPENHW "BO", 2, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    REPORT N, Y, N, N, , 0, 0, 0

JCB "1200_8FL", "ZNT_DUP"

BO "1200N1-2", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_1-2"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200N1-2", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_1-2"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200N1-2", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200N1-2", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_1-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 0

AOS "1200N1-2", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_1-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200N1-2", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_1-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "1200N1-2", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_1-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "1200N1-2", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_1-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200N1-2", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_1-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 78.00000, 10.00000, 65.00000, 86.00000, 1
    REPORT N, Y, N, N, 0, 0, 0, 5, 2, 0

AOS "1200N1-2", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_1-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "1200N1-2", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_1-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200N1-2", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_1-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 6
    INIT N, 1, 15, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AI "1200N1-2", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-16HW", "1200V1-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "%", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "1200N1-2", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-16HW", "1200V1-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AI "1200N1-2", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-16HW", "1200V1-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200N1-2", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-16HW", "1200V1-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "1200N1-2", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "1200N1-2", "KW-VFD"

BO "1200N1-1", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_1-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200N1-1", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_1-1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200N1-1", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "1200N1-1", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_1-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200N1-1", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_1-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200N1-1", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_1-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 50.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "1200N1-1", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_1-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "1200N1-1", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_1-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200N1-1", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_1-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 78.00000, 10.00000, 65.00000, 86.00000, 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AOS "1200N1-1", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_1-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "1200N1-1", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_1-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200N1-1", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_1-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AI "1200N1-1", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-16HW", "1200V1-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Hz", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "1200N1-1", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-16HW", "1200V1-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AI "1200N1-1", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-16HW", "1200V1-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200N1-1", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-16HW", "1200V1-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AD "1200N1-1", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "1200N1-1", "vfd_spd"

JCB "1200N1-1", "stpt"

JCB "1200N1-1", "KW-VFD"

BO "1200_8-8", "CRAC8-C", "CRAC-8 Enable"
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    N2OPENHW "BO", 2, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200_8-8", "CRAC8-S", "CRAC-8 Status"
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 0, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_8-8", "CRAC8-A", "CRAC-8 Alarm Status"
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 1, 30, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 6, 2, 5

BD "1200_8-8", "CRAC8OfN", "CRAC-8 Off Normal Alarm"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 11, 6, 2, 5

BD "1200_8-8", "CRAC8-HT", "CRAC-8 High Temperature"
    ASSOCINP "CS", "NC-16HW", "CRAC-Pts", "BD_4"
    GRAPHICS 0, 0
    UNITS "No", "Yes!!!"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 12, 6, 2, 5

AD "1200_8-8", "Z1-Temp", "Zone-1 Temperature"
    ASSOCINP "********", "1200_8-7", "Z1-Temp", "VALUE"
~System does not exist in archive global database
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 77.70000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AD "1200_8-8", "Z2-Temp", "Zone-2 Temperature"
    ASSOCINP "********", "1200_8-7", "Z2-Temp", "VALUE"
~System does not exist in archive global database
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 77.70000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AD "1200_8-8", "Z3-Temp", "Zone-3 Temperature"
    ASSOCINP "********", "1200_8-7", "Z3-Temp", "VALUE"
~System does not exist in archive global database
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 77.70000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BD "1200_8-8", "--------", "------------------------"
    GRAPHICS 0, 0
    UNITS "------", "-----"
    INIT N, N, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

AOS "1200_8-8", "CRAC8-AF", "CRAC-8 Air Flow Failure"
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    N2OPENHW "ADI", 42, Y
    INIT 0.0, Y, N
    UNITS "Number", 0
    REPORT N, Y, N, N, 0

CS "NC-16HW", "CRAC-Pts", "CS MODEL - CRAC FMS Rst"
    MODEL "1200_8-8"
~This Model not found in Model Database.
    HARDWARE "NC-16HW", "1200_8-8"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "BD_1", "BD_1"
    FORMAT 1

AD "NC-16HW", "NC16_Idl", "NC-16 CPU Idle Time >70%"
    ASSOCINP "AD", "NONE", "NONE", "IDLE"
    GRAPHICS 0, 0
    UNITS "%", 1, 0.0
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AI "NC-16HW", "120030A1", "Sump Package#2 30AI1"
    HARDWARE "NC-16HW", "1200_SB2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 1
    UNITS "Value", 1
    ALARMSET 1.000000, , , 100.0000, , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 5

AI "NC-16HW", "120030A2", "Sump Package#1 30AI2"
    HARDWARE "NC-16HW", "1200_SB2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Value", 1
    ALARMSET 1.000000, , , 100.0000, , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 5

AI "NC-16HW", "120063A2", "Return Pump#1 63AI2"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "AI2"
    UNITS "Value", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0,

AI "NC-16HW", "120063A3", "Return Pump#2 63AI3"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "AI3"
    UNITS "Value", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0,

BO "1200_8-6", "CRAC-SS", "CRAC Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_8-4"
    GRAPHICS 0, 0
    N2OPENHW "BD", 242, N
    UNITS "Off", "On", Y, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    FEEDBACK "1200_8-6", "CRAC-Sts", Y
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200_8-6", "CRAC-Sts", "CRAC Supply Fan Status"
    HARDWARE "NC-16HW", "1200_8-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_8-6", "CRAC-Alm", "CRAC Sup Fan Alarm Sts"
    HARDWARE "NC-16HW", "1200_8-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 7
    INIT N, 1, 120, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, , 0, 0, 5

BO "1200_8-5", "CRAC-SS", "CRAC Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_8-4"
    GRAPHICS 0, 0
    N2OPENHW "BD", 243, N
    UNITS "Off", "On", Y, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    FEEDBACK "1200_8-5", "CRAC-Sts", Y
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200_8-5", "CRAC-Sts", "CRAC Supply Fan Status"
    HARDWARE "NC-16HW", "1200_8-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 7
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_8-5", "CRAC-Alm", "CRAC Sup Fan Alarm Sts"
    HARDWARE "NC-16HW", "1200_8-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 6
    INIT N, 1, 120, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200_4FL", "--------", "730 Audio/Vidio OC Stby"
    GRAPHICS 0, 0
    UNITS "------", "-----"
    INIT N, N, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

BO "1200_4FL", "DMPR-C", "730 Damper-1/2/3 Command"
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 244, N
    UNITS "Off", "On", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200_4FL", "D1-ENDSW", "730 Damper-1 End Sw N.O."
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 0, 30, N
    UNITS "Open", "Closed"
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200_4FL", "D2-ENDSW", "730 Damper-2 End Sw N.C."
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 0, 30, N
    UNITS "Closed", "Open"
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200_4FL", "D3-ENDSW", "730 Damper-3 End Sw N.C."
    HARDWARE "NC-16HW", "1200_4-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 0, 30, N
    UNITS "Closed", "Open"
    REPORT N, Y, N, N, , 0, 0, 0

BD "1200-MIS", "EME-SHDN", "HVAC Emergency Shutdown"
    GRAPHICS 0, 0
    UNITS "Off", "On"
    INIT N, N, 1, 0, N, N
    REPORT N, Y, N, N, 43, 6, 1, 5

AI "1200-MIS", "OA-TEMP", "Outside Air Temperature"
    HARDWARE "NC-16HW", "1200_D62"
    GRAPHICS 0, 0
    DCDRHW "XTM", "AI2"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

AI "1200-MIS", "OAT-Old", "Outside Air Temperature"
    HARDWARE "NC-16HW", "1200_D56"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 4

BO "1200-MIS", "EXF-DIS1", "Exhaust Fans Disable"
    HARDWARE "NC-16HW", "1200_PH1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 244, N
    UNITS "Off", "On", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200-MIS", "FMS-RST", "Reset of Fan Alarms"
    GRAPHICS 0, 0
    UNITS "No", "Reset"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200-MIS", "FIRE-ALM", "Fire Alarm"
    HARDWARE "NC-16HW", "1200_D56"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 1, 60, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 6, 1, 4

BI "1200-MIS", "FIRE-PMP", "Fire Pump Status"
    HARDWARE "NC-16HW", "1200_D56"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 1, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, 0, 6, 1, 5

BI "1200-MIS", "722-FALM", "722 12th St Fire Alarm"
    HARDWARE "NC-16HW", "1200_1-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 0, 60, Y
    UNITS "Alarm", "Normal"
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200-MIS", "722-TALM", "722 12th St Fire Trouble"
    HARDWARE "NC-16HW", "1200_1-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 0, 60, Y
    UNITS "Alarm", "Normal"
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200-MIS", "730-FALM", "730 12th St Fire Alarm"
    HARDWARE "NC-16HW", "1200_1-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 2, 60, Y
    UNITS "Alarm", "Normal"
    REPORT N, Y, N, N, 0, 6, 1, 5

BI "1200-MIS", "GEN-RUN", "Generator Run Status"
    HARDWARE "NC-16HW", "1200_PH1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 1, 60, Y
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200-MIS", "AIR-COMP", "Air Compressor Status"
    HARDWARE "NC-16HW", "1200_8-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 30, Y
    UNITS "Normal", "Low"
    REPORT N, Y, N, N, 0, 6, 1, 5

AI "1200-MIS", "DOMWTR-P", "Domestic Water Pressure"
    HARDWARE "NC-16HW", "1200_D57"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "PSI", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 4

AI "1200-MIS", "BATRM-T", "Battery Room Temperature"
    HARDWARE "NC-16HW", "1200_D57"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 4

BO "1200-MIS", "TEF-SS", "Toilet Exhaust Fan S/S"
    HARDWARE "NC-16HW", "1200_D57"
    GRAPHICS 0, 0
    N2OPENHW "BO", 1, N
    UNITS "Off", "On", Y, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    FEEDBACK "1200-MIS", "TEF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200-MIS", "TEF-STS", "Toilet Exhaust Fan Sts"
    HARDWARE "NC-16HW", "1200_D57"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200-MIS", "SUMP-STS", "High Water Alarm"
    HARDWARE "NC-16HW", "1200_D56"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 30, Y
    UNITS "Normal", "Hi_Alm"
    REPORT N, Y, N, N, 42, 6, 1, 5

BD "1200-MIS", "SUMP1-S", "Pmps 476-2B-01 Hi Water"
    ASSOCINP "AI", "NC-16HW", "120030A2", "LO_ALARM"
    GRAPHICS 0, 0
    UNITS "Normal", "Hi_Alm"
    INIT N, N, 1, 30, Y, N
    REPORT N, Y, N, N, 40, 6, 1, 5

BI "1200-MIS", "P1SP1-S", "Package#1 SumpPump#1 Sts"
    HARDWARE "NC-16HW", "1200_SB2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 0, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200-MIS", "P1SP2-S", "Package#1 SumpPump#2 Sts"
    HARDWARE "NC-16HW", "1200_SB2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 0, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200-MIS", "SUMP2-S", "Pmps 476-2B-02 Hi Water"
    ASSOCINP "AI", "NC-16HW", "120030A1", "LO_ALARM"
    GRAPHICS 0, 0
    UNITS "Normal", "Hi_Alm"
    INIT N, N, 1, 30, Y, N
    REPORT N, Y, N, N, 41, 6, 1, 5

BI "1200-MIS", "P2SP1-S", "Package#2 SumpPump#1 Sts"
    HARDWARE "NC-16HW", "1200_SB1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 0, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200-MIS", "P2SP2-S", "Package#2 SumpPump#2 Sts"
    HARDWARE "NC-16HW", "1200_SB1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 0, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200-MIS", "SBWTR-DT", "SubBasement Water Detect"
    HARDWARE "NC-16HW", "1200_SB2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 36, 6, 1, 5

JCB "1200-MIS", "LL_CTRL"

JCB "1200-MIS", "FMS_RST"

JCB "1200-MIS", "OAT_DUP"

JCB "1200-MIS", "OAD_LOUT"

JCB "1200-MIS", "EME_SHDN"

AI "1200_3FL", "INT-ZNT", "Interior Zone Temp"
    HARDWARE "NC-16HW", "1200_D58"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "1200_3FL", "INTD-CSP", "Interior Damper Clg Stpt"
    HARDWARE "NC-16HW", "1200_D58"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 239, N
    INIT 76.00000, Y, Y
    UNITS ">Deg F", 1
    REPORT N, Y, N, N, 5

AOS "1200_3FL", "INT-DMP", "Interior Damper Command"
    HARDWARE "NC-16HW", "1200_D58"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

AI "1200_3FL", "EXT-ZNT", "Exterior Zone Temp"
    HARDWARE "NC-16HW", "1200_D58"
    GRAPHICS 0, 0
    N2OPENHW "AI", 1
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "1200_3FL", "EXTD-CSP", "Exterior Damper Clg Stpt"
    HARDWARE "NC-16HW", "1200_D58"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 240, N
    INIT 76.00000, Y, Y
    UNITS ">Deg F", 1
    REPORT N, Y, N, N, 5

AOS "1200_3FL", "EXT-DMP", "Exterior Damper Command"
    HARDWARE "NC-16HW", "1200_D58"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

AOS "1200_3FL", "EBBH-HSP", "Exterior BBH Htg Stpt"
    HARDWARE "NC-16HW", "1200_D58"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 252, N
    INIT 71.00000, Y, Y
    UNITS "<Deg F", 1
    REPORT N, Y, N, N, 5

BO "1200_3FL", "EBBH-SS", "Exterior Base Board Heat"
    HARDWARE "NC-16HW", "1200_D58"
    GRAPHICS 0, 0
    N2OPENHW "BO", 1, Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER
    REPORT N, Y, N, N, , 0, 0, 5

BO "1200_3FL", "MUF-SS", "Make-Up Air Fan S/S"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "BD", 244, N
    UNITS "Off", "On", Y, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

AI "1200_3FL", "EDH1-DAT", "EDH-1 Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "1200_3FL", "EDH1-STP", "EDH-1 Disc Air Setpoint"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 243, N
    INIT 60.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AOS "1200_3FL", "EDH1-C", "Elec Duct Heater-1 Cmd"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "% Heat", 1
    REPORT N, Y, N, N, 5

AI "1200_3FL", "EDH2-DAT", "EDH-2 Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "1200_3FL", "EDH2-STP", "EDH-2 Disc Air Setpoint"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 242, N
    INIT 78.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AOS "1200_3FL", "EDH2-C", "Elec Duct Heater-2 Cmd"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "% Heat", 1
    REPORT N, Y, N, N, 5

BD "ALM1TEST", "TEST", "Verizon - DC Alarm Test"
    GRAPHICS 0, 0
    UNITS "Off", "Test"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 100, 0, 1, 5

BD "ALM2TEST", "TEST", "Verizon - DC Alarm Test"
    GRAPHICS 0, 0
    UNITS "Off", "Test"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 100, 0, 1, 5

BO "1200_B-1", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_B-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "1200_B-1", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_B-1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200_B-1", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_B-1", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_B-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AI "1200_B-1", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_B-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "1200_B-1", "Z-STPT", "Zone Setpoint"
    HARDWARE "NC-16HW", "1200_B-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 129, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "1200_B-1", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_B-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 64.00000, 85.00000, 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AI "1200_B-1", "Z-HUMD", "Zone Humidity"
    HARDWARE "NC-16HW", "1200_B-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "% RH", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "1200_B-1", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_B-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200_B-1", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_B-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

BO "1200-SB1", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_SB1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", Y, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "1200-SB1", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_SB1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200-SB1", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200-SB1", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_SB1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AI "1200-SB1", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_SB1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "1200-SB1", "Z-STPT", "Zone Setpoint"
    HARDWARE "NC-16HW", "1200_SB1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 129, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "1200-SB1", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_SB1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 65.00000, 90.00000, 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AI "1200-SB1", "Z-HUMD", "Zone Humidity"
    HARDWARE "NC-16HW", "1200_SB1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "% RH", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "1200-SB1", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_SB1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200-SB1", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_SB1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

JCB "1200-SB1", "ZNT_DUP"

AI "1200-CHL", "L1-CHWS", "Loop 1 Chil Wtr Sup Temp"
    HARDWARE "NC-16HW", "1200_D56"
    GRAPHICS 0, 0
    N2OPENHW "AI", 1
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 4

AI "1200-CHL", "L1-CHWR", "Loop 1 Chil Wtr Ret Temp"
    HARDWARE "NC-16HW", "1200_D56"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 4

AI "1200-CHL", "L1-CHWSP", "Loop 1 CHWS Pressure"
    HARDWARE "NC-16HW", "1200_D57"
    GRAPHICS 0, 0
    N2OPENHW "AI", 1
    UNITS "PSI", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 4

AI "1200-CHL", "L1-CHWRP", "Loop 1 CHWR Pressure"
    HARDWARE "NC-16HW", "1200_D57"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "PSI", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 4

AI "1200-CHL", "L2-CHWS", "Loop 2 Chil Wtr Sup Temp"
    HARDWARE "NC-16HW", "1200_D56"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 4

AI "1200-CHL", "L2-CHWR", "Loop 2 Chil Wtr Ret Temp"
    HARDWARE "NC-16HW", "1200_D56"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 4

AI "1200-CHL", "L2-CHWSP", "Loop 2 CHWS Pressure"
    HARDWARE "NC-16HW", "1200_D57"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "PSI", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 4

AI "1200-CHL", "L2-CHWRP", "Loop 2 CHWR Pressure"
    HARDWARE "NC-16HW", "1200_D57"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "PSI", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 4

BO "1200N1-3", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_1-3"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "1200N1-3", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_1-3"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200N1-3", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200N1-3", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_1-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AI "1200N1-3", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_1-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "1200N1-3", "Z-STPT", "Zone Setpoint"
    HARDWARE "NC-16HW", "1200_1-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 129, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "1200N1-3", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_1-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , , 85.00000, 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "1200N1-3", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_1-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200N1-3", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_1-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

BO "1200-SB2", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_SB2"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "1200-SB2", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_SB2"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200-SB2", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200-SB2", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_SB2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AI "1200-SB2", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_SB2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "1200-SB2", "Z-STPT", "Zone Setpoint"
    HARDWARE "NC-16HW", "1200_SB2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 129, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 5

AI "1200-SB2", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_SB2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 65.00000, 90.00000, 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "1200-SB2", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_SB2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AI "1200_9-2", "OA-TEMP", "Outside Air Temperature"
    HARDWARE "NC-16HW", "1200_9-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 1
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

CS "1200_9-2", "ALL-PNTS", "CS MODEL- Disc Air Stpt"
    MODEL "U100%D_C"
    HARDWARE "NC-16HW", "1200_9-2"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 1

BO "1200_9-2", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_9-2"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "1200_9-2", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_9-2"
    GRAPHICS 0, 0
    N2OPENHW "BO", 1, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200_9-2", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_9-2", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_9-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AI "1200_9-2", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_9-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "1200_9-2", "WTR-DET", "Water Detection Status"
    HARDWARE "NC-16HW", "1200_9-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, , 0, 0, 5

BO "1200_9-2", "MOAD-CMD", "Minimum OA Damper Cmd"
    HARDWARE "NC-16HW", "1200_9-2"
    GRAPHICS 0, 0
    N2OPENHW "BO", 2, Y
    UNITS "Closed", "Open", N, Y, N
    RESET Y
    TIMER
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200_9-2", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_9-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, Y, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

AOS "1200_9-2", "F&B-DMP", "Face & Bypass Dmp Cmd"
    HARDWARE "NC-16HW", "1200_9-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, Y, N
    UNITS "% Face", 1
    REPORT N, Y, N, N, 5

CS "1200_9-4", "ALL-PNTS", "CS MODEL - Zone Setpoint"
    MODEL "U_TU_C"
    HARDWARE "NC-16HW", "1200_9-4"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 1

BO "1200_9-4", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_9-4"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "1200_9-4", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_9-4"
    GRAPHICS 0, 0
    N2OPENHW "BO", 1, Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER
    FEEDBACK "1200_9-4", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_9-4", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_9-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AI "1200_9-4", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_9-4"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "1200_9-4", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_9-4"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

BD "1200_GEN", "--------", "   Generator-1 Points"
    GRAPHICS 0, 0
    UNITS "------", "-----"
    INIT N, N, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

AI "1200_GEN", "GENRM1-T", "Generator Rm 1 Temp"
    HARDWARE "NC-16HW", "1200_D62"
    GRAPHICS 0, 0
    DCDRHW "XTM", "AI1"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

BI "1200_GEN", "GN1-STS", "Generator-1 Run Status"
    HARDWARE "NC-16HW", "1200_D62"
    GRAPHICS 0, 0
    DCDRHW "XTM", "2DI5"
    INIT N, 1, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, 0, 0, 2,

BI "1200_GEN", "GN1-FAIL", "Generator-1 Failure Sts"
    HARDWARE "NC-16HW", "1200_D62"
    GRAPHICS 0, 0
    DCDRHW "XTM", "2DI3"
    INIT N, 1, 30, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "GN1-EPO", "Generator-1 EPO Status"
    HARDWARE "NC-16HW", "1200_D62"
    GRAPHICS 0, 0
    DCDRHW "XTM", "2DI4"
    INIT N, 1, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "GN1-DDPR", "Generator-1 Disc Dpr Sts"
    HARDWARE "NC-16HW", "1200_D62"
    GRAPHICS 0, 0
    DCDRHW "XTM", "1DI1"
    INIT N, 0, 30, N
    UNITS "Closed", "Open"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "GN1-LDPR", "Generator-1 Lowr Dpr Sts"
    HARDWARE "NC-16HW", "1200_D62"
    GRAPHICS 0, 0
    DCDRHW "XTM", "1DI3"
    INIT N, 0, 30, N
    UNITS "Closed", "Open"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "GN1-UDPR", "Generator-1 Uppr Dpr Sts"
    HARDWARE "NC-16HW", "1200_D62"
    GRAPHICS 0, 0
    DCDRHW "XTM", "1DI2"
    INIT N, 0, 30, N
    UNITS "Closed", "Open"
    REPORT N, Y, N, N, , 0, 0,

AD "1200_GEN", "EF1-STPT", "Exh Fan-1 Setpoint"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 100.0000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, , , 0, 0, 0, 5

BO "1200_GEN", "EF1-SS", "Exh Fan-1 S/S"
    HARDWARE "NC-16HW", "1200_9-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 244, N
    UNITS "Off", "On", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    FEEDBACK "1200_GEN", "EF1-STS", Y
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200_GEN", "EF1-STS", "Exh Fan-1 Status"
    HARDWARE "NC-16HW", "1200_D62"
    GRAPHICS 0, 0
    DCDRHW "XTM", "2DI1"
    INIT N, 1, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "EF1-DPR", "Exh Fan-1 Damper Sts"
    HARDWARE "NC-16HW", "1200_D62"
    GRAPHICS 0, 0
    DCDRHW "XTM", "1DI4"
    INIT N, 0, 30, N
    UNITS "Closed", "Open"
    REPORT N, Y, N, N, , 0, 0,

BD "1200_GEN", "-------", "   Generator-2 Points"
    GRAPHICS 0, 0
    UNITS "------", "-----"
    INIT N, N, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

BI "1200_GEN", "GN2-STS", "Generator-2 Run Status"
    HARDWARE "NC-16HW", "1200_D62"
    GRAPHICS 0, 0
    DCDRHW "XTM", "2DI8"
    INIT N, 1, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "GN2-FAIL", "Generator-2 Failure Sts"
    HARDWARE "NC-16HW", "1200_D62"
    GRAPHICS 0, 0
    DCDRHW "XTM", "2DI6"
    INIT N, 1, 30, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "GN2-EPO", "Generator-2 EPO Status"
    HARDWARE "NC-16HW", "1200_D62"
    GRAPHICS 0, 0
    DCDRHW "XTM", "2DI7"
    INIT N, 1, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "GN2-DDPR", "Generator-2 Disc Dpr Sts"
    HARDWARE "NC-16HW", "1200_D62"
    GRAPHICS 0, 0
    DCDRHW "XTM", "1DI5"
    INIT N, 0, 30, N
    UNITS "Closed", "Open"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "GN2-LDPR", "Generator-2 Lowr Dpr Sts"
    HARDWARE "NC-16HW", "1200_D62"
    GRAPHICS 0, 0
    DCDRHW "XTM", "1DI7"
    INIT N, 0, 30, N
    UNITS "Closed", "Open"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "GN2-UDPR", "Generator-2 Uppr Dpr Sts"
    HARDWARE "NC-16HW", "1200_D62"
    GRAPHICS 0, 0
    DCDRHW "XTM", "1DI6"
    INIT N, 0, 30, N
    UNITS "Closed", "Open"
    REPORT N, Y, N, N, , 0, 0,

AD "1200_GEN", "EF2-STPT", "Exh Fan-2 Setpoint"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 100.0000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, , , 0, 0, 0, 5

BO "1200_GEN", "EF2-SS", "Exh Fan-2 S/S"
    HARDWARE "NC-16HW", "1200_9-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 243, N
    UNITS "Off", "On", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    FEEDBACK "1200_GEN", "EF2-STS", Y
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200_GEN", "EF2-STS", "Exh Fan-2 Status"
    HARDWARE "NC-16HW", "1200_D62"
    GRAPHICS 0, 0
    DCDRHW "XTM", "2DI2"
    INIT N, 1, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "EF2-DPR", "Exh Fan-2 Damper Sts"
    HARDWARE "NC-16HW", "1200_D62"
    GRAPHICS 0, 0
    DCDRHW "XTM", "1DI8"
    INIT N, 0, 30, N
    UNITS "Closed", "Open"
    REPORT N, Y, N, N, , 0, 0,

BD "1200_GEN", "------", "   Generator-3 Points"
    GRAPHICS 0, 0
    UNITS "------", "-----"
    INIT N, N, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

AI "1200_GEN", "GENRM2-T", "Generator Rm 2 Temp"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "AI1"
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

BI "1200_GEN", "GN3-STS", "Generator-3 Run Status"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "1DI3"
    INIT N, 1, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "GN3-FAIL", "Generator-3 Failure Sts"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "1DI1"
    INIT N, 1, 30, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "GN3-EPO", "Generator-3 EPO Status"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "1DI2"
    INIT N, 1, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "GN3-DDPR", "Generator-3 Disc Dpr Sts"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "1DI4"
    INIT N, 0, 30, N
    UNITS "Closed", "Open"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "GN3-LDPR", "Generator-3 lowr Dpr Sts"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "1DI6"
    INIT N, 0, 30, N
    UNITS "Closed", "Open"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "GN3-UDPR", "Generator-3 Uppr Dpr Sts"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "1DI5"
    INIT N, 0, 30, N
    UNITS "Closed", "Open"
    REPORT N, Y, N, N, , 0, 0,

AD "1200_GEN", "EF3-STPT", "Exh Fan-3 Setpoint"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 85.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, , , 0, 0, 0, 5

BO "1200_GEN", "EF3-SS", "Exh Fan-3 S/S"
    HARDWARE "NC-16HW", "1200_9-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 242, N
    UNITS "Off", "On", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    FEEDBACK "1200_GEN", "EF3-STS", Y
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200_GEN", "EF3-STS", "Exh Fan-3 Status"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "1DI8"
    INIT N, 1, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "EF3-DPR", "Exh Fan-3 Damper Status"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "1DI7"
    INIT N, 0, 30, N
    UNITS "Closed", "Open"
    REPORT N, Y, N, N, , 0, 0,

BD "1200_GEN", "-----", "    Day Tank Points"
    GRAPHICS 0, 0
    UNITS "------", "-----"
    INIT N, N, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

AI "1200_GEN", "DT1-LEV", "Day Tank-1 Level"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "AI5"
    UNITS "% Full", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

BI "1200_GEN", "DT1-LOW", "Day Tank-1 Low Level Sts"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "2DI1"
    INIT N, 1, 30, N
    UNITS "Normal", "Low"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "DT1-HIGH", "Day Tank-1 Hi Level Sts"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "2DI2"
    INIT N, 1, 30, N
    UNITS "Normal", "High"
    REPORT N, Y, N, N, , 0, 0,

AI "1200_GEN", "DT2-LEV", "Day Tank-2 Level"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "AI6"
    UNITS "% Full", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2,

BI "1200_GEN", "DT2-LOW", "Day Tank-2 Low Level Sts"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "2DI3"
    INIT N, 1, 30, N
    UNITS "Normal", "Low"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "DT2-HIGH", "Day Tank-2 Hi Level Sts"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "2DI4"
    INIT N, 1, 30, N
    UNITS "Normal", "High"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "OP8A-STS", "Oil Pump-8A Status"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "2DI5"
    INIT N, 0, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "OP8B-STS", "Oil Pump-8B Status"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "2DI6"
    INIT N, 0, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "OP9A-STS", "Oil Pump-9A Status"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "2DI7"
    INIT N, 0, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

BI "1200_GEN", "OP9B-STS", "Oil Pump-9B Status"
    HARDWARE "NC-16HW", "1200_D63"
    GRAPHICS 0, 0
    DCDRHW "XTM", "2DI8"
    INIT N, 0, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0,

JCB "1200_GEN", "EXH_FANS"

BI "1200_GEN", "FOLeak-N", "Fuel Oil Leak Sens North"
    HARDWARE "NC-16HW", "1200_D67"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 0, 30, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_GEN", "FOLeak-S", "Fuel Oil Leak Sens South"
    HARDWARE "NC-16HW", "1200_D67"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200_GEN", "ROP1-STS", "Return Oil Pump-1 Status"
    GRAPHICS 0, 0
    UNITS "Off", "On"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200_GEN", "ROP2-STS", "Return Oil Pump-2 Status"
    GRAPHICS 0, 0
    UNITS "Off", "On"
    INIT N, N, 0, 30, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200_9FL", "--------", "Bsmt Fuel Oil Pump Room"
    GRAPHICS 0, 0
    UNITS "------", "-----"
    INIT N, N, 0, 30, N, N
    REPORT N, N, , N, , 0, 0, 0

BO "1200_9FL", "SF1-SS", "Supply Fan-1 S/S"
    HARDWARE "NC-16HW", "1200_9-4"
    GRAPHICS 0, 0
    N2OPENHW "BO", 4, N
    UNITS "Off", "On", Y, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    FEEDBACK "1200_9FL", "SF1-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_9FL", "SF1-STS", "Supply Fan-1 Status"
    HARDWARE "NC-16HW", "1200_9-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BO "1200_9FL", "SF1-OAD", "Supply Fan-1 OA Dmp Cmd"
    HARDWARE "NC-16HW", "1200_9-4"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Closed", "Open", N, Y, N
    RESET Y
    TIMER
    REPORT N, Y, N, N, , 0, 0, 5

BO "1200_2-1", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_2-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200_2-1", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_2-1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200_2-1", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "1200_2-1", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_2-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200_2-1", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_2-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_2-1", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_2-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 42.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "1200_2-1", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_2-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "1200_2-1", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_2-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_2-1", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_2-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 78.00000, 10.00000, 65.00000, 86.00000, 1
    REPORT N, Y, N, N, 0, 0, 0, 2, 2, 0

AOS "1200_2-1", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_2-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

AI "1200_2-1", "Z-HUMD", "Zone Humidity"
    HARDWARE "NC-16HW", "1200_2-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "% RH", 1
    ALARMSET , 70.00000, 70.00000, , , 2
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "1200_2-1", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_2-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_2-1", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_2-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AI "1200_2-1", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-16HW", "1200V2-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "HZ", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_2-1", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-16HW", "1200V2-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_2-1", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-16HW", "1200V2-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "1200_2-1", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-16HW", "1200V2-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AD "1200_2-1", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "1200_2-1", "KW-VFD"

JCB "1200_2-1", "vfd_spd"

JCB "1200_2-1", "stpt"

BO "1200_2-2", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_2-2"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200_2-2", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_2-2"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200_2-2", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "1200_2-2", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_2-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200_2-2", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_2-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_2-2", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_2-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 42.00000, 85.00000, 1
    REPORT N, Y, N, N, , , 6, 0, 0, 5

AOS "1200_2-2", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_2-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "1200_2-2", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_2-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_2-2", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_2-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 78.00000, 10.00000, 65.00000, 86.00000, 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "1200_2-2", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_2-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "1200_2-2", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_2-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_2-2", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_2-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AI "1200_2-2", "VFD_FB", "VFD-FEEDBACK"
    HARDWARE "NC-16HW", "1200V2-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "HZ", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_2-2", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-16HW", "1200V2-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_2-2", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-16HW", "1200V2-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "1200_2-2", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-16HW", "1200V2-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AD "1200_2-2", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 5.000000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "1200_2-2", "KW-VFD"

BO "1200_3-1", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_3-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200_3-1", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_3-1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER
    FEEDBACK "1200_3-1", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "1200_3-1", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_3-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200_3-1", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_3-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_3-1", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_3-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "1200_3-1", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_3-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "1200_3-1", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_3-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_3-1", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_3-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 78.00000, 10.00000, 65.00000, 86.00000, 1
    REPORT N, Y, N, N, 0, 0, 0, 2, 2, 0

AOS "1200_3-1", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_3-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

AI "1200_3-1", "Z-HUMD", "Zone Humidity"
    HARDWARE "NC-16HW", "1200_3-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "% RH", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "1200_3-1", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_3-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_3-1", "WTR-DET", "Water Detection Status"
    HARDWARE "NC-16HW", "1200_3-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 36, 6, 2, 5

BI "1200_3-1", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_3-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 15, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

CS "1200_3-1", "ALL-PNTS", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-16HW", "1200_3-1"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

AI "1200_3-1", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-16HW", "1200V31B"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "HZ", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_3-1", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-16HW", "1200V31B"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_3-1", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-16HW", "1200V31B"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "1200_3-1", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-16HW", "1200V31B"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AD "1200_3-1", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "1200_3-1", "KW-VFD"

JCB "1200_3-1", "vfd_spd"

JCB "1200_3-1", "stpt"

BO "1200_3-2", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_3-2"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200_3-2", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_3-2"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER
    FEEDBACK "1200_3-2", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "1200_3-2", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_3-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200_3-2", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_3-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_3-2", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_3-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "1200_3-2", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_3-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "1200_3-2", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_3-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_3-2", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_3-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 78.00000, 10.00000, 65.00000, 86.00000, 1
    REPORT N, Y, N, N, 0, 0, 0, 2, 2, 0

AOS "1200_3-2", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_3-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

AI "1200_3-2", "Z-HUMD", "Zone Humidity"
    HARDWARE "NC-16HW", "1200_3-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "% RH", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "1200_3-2", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_3-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_3-2", "WTR-DET", "Water Detection Status"
    HARDWARE "NC-16HW", "1200_3-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 36, 6, 2, 5

BI "1200_3-2", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_3-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 15, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

CS "1200_3-2", "ALL-PNTS", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-16HW", "1200_3-2"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

AI "1200_3-2", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-16HW", "1200V32B"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "HZ", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_3-2", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-16HW", "1200V32B"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_3-2", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-16HW", "1200V32B"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "1200_3-2", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-16HW", "1200V32B"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AD "1200_3-2", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "1200_3-2", "KW-VFD"

BO "1200_3-3", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200_3-3", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER
    FEEDBACK "1200_3-3", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "1200_3-3", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200_3-3", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_3-3", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "1200_3-3", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 4, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "1200_3-3", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 236, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_3-3", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 78.00000, 10.00000, 65.00000, 86.00000, 1
    REPORT N, Y, N, N, 0, 0, 0, 2, 2, 0

AOS "1200_3-3", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 3, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "1200_3-3", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_3-3", "WTR-DET", "Water Detection Status"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 36, 6, 2, 5

BI "1200_3-3", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 15, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

CS "1200_3-3", "ALL-PNTS", "CS MODEL - Act Dis Stpt"
    MODEL "U_100%1C"
    HARDWARE "NC-16HW", "1200_3-3"
    GRAPHICS 0, 0
    REPORT N, N, 0
    DISPLAY "SP_2", "SP_2"
    FORMAT 1

AI "1200_3-3", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-16HW", "1200V33B"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "HZ", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_3-3", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-16HW", "1200V33B"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_3-3", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-16HW", "1200V33B"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "1200_3-3", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-16HW", "1200V33B"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AD "1200_3-3", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "1200_3-3", "KW-VFD"

BO "1200_4-3", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_4-3"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200_4-3", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_4-3"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200_4-3", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "1200_4-3", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_4-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200_4-3", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_4-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_4-3", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_4-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 0.1000000, , , 45.00000, 70.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "1200_4-3", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_4-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "1200_4-3", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_4-3"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_4-3", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_4-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 76.00000, 10.00000, 65.00000, 86.00000, 1
    REPORT N, Y, N, N, 0, 0, 0, 5, 2, 0

AOS "1200_4-3", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_4-3"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "1200_4-3", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_4-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_4-3", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_4-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AI "1200_4-3", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-16HW", "1200V4-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "HZ", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_4-3", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-16HW", "1200V4-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_4-3", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-16HW", "1200V4-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "1200_4-3", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-16HW", "1200V4-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 0

AD "1200_4-3", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 100.0000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "1200_4-3", "KW-VFD"

JCB "1200_4-3", "vfd_spd"

JCB "1200_4-3", "stpt"

BO "1200N7-2", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_7-2"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200N7-2", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_7-2"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200N7-2", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "1200N7-2", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_7-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200N7-2", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_7-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200N7-2", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_7-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , , 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "1200N7-2", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_7-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "1200N7-2", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_7-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200N7-2", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_7-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 75.00000, 10.00000, 60.00000, 86.00000, 1
    REPORT N, Y, N, N, 0, 0, 0, 2, 2, 0

AOS "1200N7-2", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_7-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "1200N7-2", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_7-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200N7-2", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_7-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AI "1200N7-2", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-16HW", "1200V7-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "HZ", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200N7-2", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-16HW", "1200V7-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200N7-2", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-16HW", "1200V7-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "1200N7-2", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-16HW", "1200V7-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AD "1200N7-2", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "1200N7-2", "KW-VFD"

BO "1200N5-1", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_5-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200N5-1", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_5-1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200N5-1", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "1200N5-1", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_5-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 0

AOS "1200N5-1", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_5-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200N5-1", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_5-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "1200N5-1", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_5-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "1200N5-1", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_5-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200N5-1", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_5-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 78.00000, 10.00000, 62.00000, 86.00000, 1
    REPORT N, Y, N, N, 0, 0, 0, 2, 2, 0

AOS "1200N5-1", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_5-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

AI "1200N5-1", "Z-HUMD", "Zone Humidity"
    HARDWARE "NC-16HW", "1200_5-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "% RH", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "1200N5-1", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_5-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200N5-1", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_5-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AI "1200N5-1", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-16HW", "1200V5-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "HZ", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200N5-1", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-16HW", "1200V5-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200N5-1", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-16HW", "1200V5-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "1200N5-1", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-16HW", "1200V5-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AD "1200N5-1", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "1200N5-1", "KW-VFD"

JCB "1200N5-1", "vfd_spd"

JCB "1200N5-1", "stpt"

BO "1200_5-2", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_5-2"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200_5-2", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_5-2"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200_5-2", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "1200_5-2", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_5-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200_5-2", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_5-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_5-2", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_5-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "1200_5-2", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_5-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "1200_5-2", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_5-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_5-2", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_5-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 78.00000, 10.00000, 61.00000, 86.00000, 1
    REPORT N, Y, N, N, 0, 0, 0, 2, 2, 0

AOS "1200_5-2", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_5-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

BI "1200_5-2", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_5-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_5-2", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_5-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AI "1200_5-2", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-16HW", "1200V5-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "HZ", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_5-2", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-16HW", "1200V5-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_5-2", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-16HW", "1200V5-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "1200_5-2", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-16HW", "1200V5-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AD "1200_5-2", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "1200_5-2", "KW-VFD"

BO "1200N7-1", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_7-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 0

BO "1200N7-1", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_7-1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200N7-1", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "1200N7-1", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_7-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 1, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200N7-1", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_7-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200N7-1", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_7-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, , 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "1200N7-1", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_7-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "1200N7-1", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_7-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200N7-1", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_7-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 75.00000, 10.00000, 60.00000, 86.00000, 1
    REPORT N, Y, N, N, 0, 0, 0, 2, 2, 0

AOS "1200N7-1", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_7-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

AI "1200N7-1", "Z-HUMD", "Zone Humidity"
    HARDWARE "NC-16HW", "1200_7-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "% RH", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "1200N7-1", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_7-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200N7-1", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_7-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 10, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AI "1200N7-1", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-16HW", "1200V7-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "HZ", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200N7-1", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-16HW", "1200V7-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200N7-1", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-16HW", "1200V7-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "1200N7-1", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-16HW", "1200V7-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "OFF", "ON"
    REPORT N, Y, N, N, , 0, 0, 0

AD "1200N7-1", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

BI "1200N7-1", "WTR-DET", "Floor Water Detector"
    HARDWARE "NC-16HW", "1200_7-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 11, 0, 2, 0

JCB "1200N7-1", "KW-VFD"

JCB "1200N7-1", "vfd_spd"

JCB "1200N7-1", "stpt"

BD "ALM3TEST", "TEST", "Verizon - Cary Alm Test"
    GRAPHICS 0, 0
    UNITS "Off", "Test"
    INIT N, N, 1, 30, N, N
    REPORT N, Y, N, N, 99, 0, 1, 5

AI "1200_9-1", "OA-TEMP", "Outside Air Temperature"
    HARDWARE "NC-16HW", "1200_9-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 1
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

CS "1200_9-1", "ALL-PNTS", "CS MODEL - Disc Air Stpt"
    MODEL "U_MASPbC"
    HARDWARE "NC-16HW", "1200_9-1"
    GRAPHICS 0, 0
    REPORT N, N, 5
    DISPLAY "SP_1", "SP_1"
    FORMAT 1

BO "1200_9-1", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_9-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "1200_9-1", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_9-1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 1, Y
    UNITS "Off", "On", N, Y, N
    RESET N
    TIMER
    FEEDBACK "1200_9-1", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_9-1", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_9-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AI "1200_9-1", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_9-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AI "1200_9-1", "MA-TEMP", "Mixed Air Temperature"
    HARDWARE "NC-16HW", "1200_9-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "1200_9-1", "RACO2-SP", "Return Air CO2 Setpoint"
    HARDWARE "NC-16HW", "1200_9-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 153, N
    INIT 900.0000, Y, Y
    UNITS "PPM", 0
    REPORT N, Y, N, N, 5

AI "1200_9-1", "RA-CO2", "Return Air CO2 Reading"
    HARDWARE "NC-16HW", "1200_9-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "PPM", 0
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "1200_9-1", "WTR-DET", "Water Detection Status"
    HARDWARE "NC-16HW", "1200_9-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 5

AOS "1200_9-1", "DMP-CMD", "Damper Command"
    HARDWARE "NC-16HW", "1200_9-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

AOS "1200_9-1", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_9-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AI "1200_4-1", "OA-TEMP", "Outside Air Temperature"
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 1
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BO "1200_4-1", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "1200_4-1", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200_4-1", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "1200_4-1", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 0

AOS "1200_4-1", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_4-1", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "1200_4-1", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "1200_4-1", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_4-1", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 78.00000, 10.00000, 65.00000, 86.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "1200_4-1", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 3, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

AI "1200_4-1", "MA-TEMP", "Mixed Air Temperature"
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "1200_4-1", "RACO2-SP", "Return Air CO2 Setpoint"
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 153, N
    INIT 900.0000, Y, Y
    UNITS "PPM", 0
    REPORT N, Y, N, N, 5

AI "1200_4-1", "RA-CO2", "Return Air CO2 Reading"
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "PPM", 0
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "1200_4-1", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200_4-1", "DMP-CMD", "Damper Command"
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 5

BI "1200_4-1", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_4-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 6
    INIT N, 1, 15, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AI "1200_4-1", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-16HW", "1200V4-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "HZ", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_4-1", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-16HW", "1200V4-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_4-1", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-16HW", "1200V4-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "1200_4-1", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-16HW", "1200V4-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 0

AD "1200_4-1", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "1200_4-1", "KW-VFD"

JCB "1200_4-1", "vfd_spd"

JCB "1200_4-1", "stpt"

AI "1200_4-2", "OA-TEMP", "Outside Air Temperature"
    HARDWARE "NC-16HW", "1200_4-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 1
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BO "1200_4-2", "SHUTDOWN", "Shutdown Mode S/S"
    HARDWARE "NC-16HW", "1200_4-2"
    GRAPHICS 0, 0
    N2OPENHW "BD", 197, N
    UNITS "No", "Yes", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    REPORT N, Y, N, N, , 0, 0, 5

BO "1200_4-2", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_4-2"
    GRAPHICS 0, 0
    N2OPENHW "BO", 3, Y
    UNITS "Off", "On", N, Y, N
    RESET Y
    TIMER
    FEEDBACK "1200_4-2", "SAF-STS", Y
    REPORT N, Y, N, N, 0, 0, 2, 0

BI "1200_4-2", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_4-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

AOS "1200_4-2", "DA-Sp", "Dis Stpt (for Clg Vlv)"
    HARDWARE "NC-16HW", "1200_4-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 142, N
    INIT 55.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_4-2", "DA-TEMP", "Discharge Air Temp"
    HARDWARE "NC-16HW", "1200_4-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET 2.000000, , , 45.00000, 85.00000, 1
    REPORT N, Y, N, N, , 0, 0, 0, 2, 0

AOS "1200_4-2", "CLGV-CMD", "Cooling Valve Command"
    HARDWARE "NC-16HW", "1200_4-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 2, Y
    INIT 0.0, N, N
    UNITS "%Open", 1
    REPORT N, Y, N, N, 5

AOS "1200_4-2", "Zn-Sp", "Zone Stpt (for VFD)"
    HARDWARE "NC-16HW", "1200_4-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 248, N
    INIT 80.00000, Y, Y
    UNITS "Deg F", 1
    REPORT N, Y, N, N, 0

AI "1200_4-2", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_4-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 4
    UNITS "Deg F", 1
    ALARMSET 1.000000, 78.00000, 10.00000, 65.00000, 86.00000, 1
    REPORT N, Y, N, N, 0, 0, 0, 2, 2, 0

AOS "1200_4-2", "VFD-O", "VFD Cmd 0=18Hz 100=60Hz"
    HARDWARE "NC-16HW", "1200_4-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 1, Y
    INIT 0.0, N, N
    UNITS "%", 1
    REPORT N, Y, N, N, 0

AI "1200_4-2", "MA-TEMP", "Mixed Air Temperature"
    HARDWARE "NC-16HW", "1200_4-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

AOS "1200_4-2", "RACO2-SP", "Return Air CO2 Setpoint"
    HARDWARE "NC-16HW", "1200_4-2"
    GRAPHICS 0, 0
    N2OPENHW "ADF", 153, N
    INIT 900.0000, Y, Y
    UNITS "PPM", 0
    REPORT N, Y, N, N, 5

AI "1200_4-2", "RA-CO2", "Return Air CO2 Reading"
    HARDWARE "NC-16HW", "1200_4-2"
    GRAPHICS 0, 0
    N2OPENHW "AI", 5
    UNITS "PPM", 0
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 0, 0, 6, 3, 2, 5

BI "1200_4-2", "FILTER", "Filter Status"
    HARDWARE "NC-16HW", "1200_4-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Clean", "Dirty"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_4-2", "VFD-A", "VFD Alarm"
    HARDWARE "NC-16HW", "1200_4-2"
    GRAPHICS 0, 0
    N2OPENHW "BI", 4
    INIT N, 1, 15, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 0, 0, 2, 0

AOS "1200_4-2", "DMP-CMD", "Damper Command"
    HARDWARE "NC-16HW", "1200_4-2"
    GRAPHICS 0, 0
    N2OPENHW "AO", 4, Y
    INIT 0.0, N, N
    UNITS "% Open", 1
    REPORT N, Y, N, N, 0

AI "1200_4-2", "VFD-FB", "VFD-FEEDBACK"
    HARDWARE "NC-16HW", "1200V4-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 2
    UNITS "HZ", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_4-2", "VFD-AMPS", "VFD-MOTOR CURRENT"
    HARDWARE "NC-16HW", "1200V4-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 6
    UNITS "A", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

AI "1200_4-2", "VFD-VLTS", "VFD-MOTOR VOLTS"
    HARDWARE "NC-16HW", "1200V4-1"
    GRAPHICS 0, 0
    N2OPENHW "AI", 8
    UNITS "V", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, , , 0, 0, 0, 0

BI "1200_4-2", "VFD-STS", "VFD-STATUS"
    HARDWARE "NC-16HW", "1200V4-1"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 0, 30, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 0

AD "1200_4-2", "VFD-KW", "VFD-KW"
    GRAPHICS 0, 0
    UNITS "KW", 1, 55.00000
    ALARMSET , , , , , 1, N
    REPORT N, N, , N, , , 0, 0, 0, 0

JCB "1200_4-2", "KW-VFD"

BO "1200_8-3", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_8-3"
    GRAPHICS 0, 0
    N2OPENHW "BD", 244, N
    UNITS "Off", "On", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    FEEDBACK "1200_8-3", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 0

BI "1200_8-3", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_8-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 2, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_8-3", "SAF-ALM", "Supply Fan Alarm Status"
    HARDWARE "NC-16HW", "1200_8-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 1, 30, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, , 6, 0, 5

BD "1200_8-3", "LEAD", "Lead Unit"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, Y, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200_8-3", "STANDBY", "Standby for 8-4"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200_8-3", "OFF-NORM", "Unit Off Normal"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 1, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200_8-3", "HI-TEMP", "Unit High Temp"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 1, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

AD "1200_8-3", "LEAD-HLS", "Lead High Limit For Sby"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 83.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 4, 3, 5

AI "1200_8-3", "Z-TEMP", "Zone Temperature"
    HARDWARE "NC-16HW", "1200_8-3"
    GRAPHICS 0, 0
    N2OPENHW "AI", 3
    UNITS "Deg F", 1
    ALARMSET , , , , , 1
    REPORT N, Y, N, N, 31, 31, 6, 3, 2, 5

BI "1200_8-3", "WTR-DET", "Water Detector Status"
    HARDWARE "NC-16HW", "1200_8-3"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 6, 6, 2, 5

JCB "1200_8-3", "HI_TEMP"

JCB "1200_8-3", "OFF_NORM"

JCB "1200_8-3", "SAF_SS"

BO "1200_8-4", "SAF-SS", "Supply Fan S/S"
    HARDWARE "NC-16HW", "1200_8-4"
    GRAPHICS 0, 0
    N2OPENHW "BD", 244, N
    UNITS "Off", "On", N, Y, Y
    RESET Y
    TIMER 5, 1, 0, 255
    FEEDBACK "1200_8-4", "SAF-STS", Y
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_8-4", "SAF-STS", "Supply Fan Status"
    HARDWARE "NC-16HW", "1200_8-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 1
    INIT N, 1, 120, N
    UNITS "Off", "On"
    REPORT N, Y, N, N, , 0, 0, 5

BI "1200_8-4", "SAF-ALM", "Supply Fan Alarm Status"
    HARDWARE "NC-16HW", "1200_8-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 2
    INIT N, 1, 120, N
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200_8-4", "LEAD", "Lead Unit"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200_8-4", "STANDBY", "Standby for 8-3"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 0, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200_8-4", "OFF-NORM", "Unit Off Normal"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 1, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

BD "1200_8-4", "HI-TEMP", "Unit High Temp"
    GRAPHICS 0, 0
    UNITS "No", "Yes"
    INIT N, N, 1, 0, N, N
    REPORT N, Y, N, N, , 0, 0, 5

AD "1200_8-4", "LEAD-HLS", "Lead High Limit For Sby"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 83.00000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 0, 0, 6, 4, 3, 5

AD "1200_8-4", "Z-TEMP", "Zone Temperature"
    ASSOCINP "AI", "1200_8-3", "Z-TEMP", "VALUE"
    GRAPHICS 0, 0
    UNITS "Deg F", 1, 77.70000
    ALARMSET , , , , , 1, N
    REPORT N, Y, N, N, 31, 31, 6, 3, 2, 5

BI "1200_8-4", "WTR-DET", "Water Detector Status"
    HARDWARE "NC-16HW", "1200_8-4"
    GRAPHICS 0, 0
    N2OPENHW "BI", 3
    INIT N, 1, 15, Y
    UNITS "Normal", "Alarm"
    REPORT N, Y, N, N, 6, 6, 2, 5

JCB "1200_8-4", "HI_TEMP"

JCB "1200_8-4", "OFF_NORM"

JCB "1200_8-4", "SAF_SS"

******************************************************************************
*
*                      SUMMARY FOR BELLATL NC-16
*
*                            HARDWARE OBJECTS
*
*        D600s   0          DCDRs   2           DCMs   0        DCM140s   0   
*         DSCs   0       DSC8500s   0          FIREs   0           FPUs   0   
*         LCDs   0           LONs   0        N2OPENs  55            XMs   0   
*
*  Total Hardware Objects = 57
*
*
*                            SOFTWARE OBJECTS
*
*        ACMs   0            ADs  33**          AIs 165           AODs   0   
*        AOSs 124**          BDs  44**          BIs 170            BOs  74   
*      C210As   0         C260As   0         C260Xs   0         C500Xs   0   
*         CSs  31**        DLLRs   0           JCBs  63           LCGs   0   
*         MCs   0           MSDs   0           MSIs   0           MSOs   0   
*       PIDLs   0        READERs   0          ZONEs   0   
*
*  Total Software Objects = 704
*
*  Total Objects = 761 ** object counts followed by ** signify
*                        object types which had errors
*
*
*                                FEATURES 
*
*       CARDs   0      TIMEZONEs   0   
*
*  Total Features = 0
*
******************************************************************************
* 12 errors decompiling - Decompiled source has errors that will not compile
******************************************************************************
